baseurl: http://www.catbird-analytics.com
title: Catbird Analytics
languageCode: en-us
paginate: '5'
theme: Mainroad
disqusShortname: ''
googleAnalytics: 'UA-219000950-1'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  /: /:slug/
  posts: /:slug/
Author:
  avatar: img/avatar.png
  bio: I'm passionate about using data and analytics to understand the world better, improve decision-making, and more effectively achieve goals.
  name: John Yuill
Params:
  authorbox: yes
  description: John Yuill's professional data analytics blog.
  logo:
    subtitle: Digital Analytics from the Catbird Seat
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
    - description
    - thumbnail
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - social
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
    social:
      github: 'jyuill'
      linkedin: 'johnyuill'
      #custom:
      #  - title: 'Home'
      #    url: 'index.html'
        
  style:
    vars:  
      highlightColor: '#2d81e2'  # Override highlight color (orig: '#e22d30')
    
markup:
  goldmark:
    renderer:
      unsafe: true
