baseurl: /
title: Catbird Analytics
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author:
  avatar: img/avatar.png
  bio: John Yuill is passionate about using data and analytics.
  name: John Yuill
Params:
  authorbox: yes
  description: John Yuill's professional data analytics blog.
  logo:
    subtitle: Analytics from the Catbird Seat
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
