<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>R Time Series Objects vs Data Frames: Advantages and Limitations - Catbird Analytics</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="Exploration of time series objects strengths and limitations relative to data frames in R.">
		<meta property="og:title" content="R Time Series Objects vs Data Frames: Advantages and Limitations" />
<meta property="og:description" content="Exploration of time series objects strengths and limitations relative to data frames in R." />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/" /><meta property="article:section" content="post" />
<meta property="article:published_time" content="2022-01-30T00:00:00+00:00" />
<meta property="article:modified_time" content="2022-01-30T00:00:00+00:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-219000950-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>


	
  
<script async src="https://www.googletagmanager.com/gtag/js?id=G-5XF0SHH0KW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-5XF0SHH0KW');
</script>
  
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="Catbird Analytics" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">Catbird Analytics</div>
					<div class="logo__tagline">Digital Analytics from the Catbird Seat</div>
				</div>
		</a>
	</div>
		
<nav class="menu">
	<button class="menu__btn" aria-haspopup="true" aria-expanded="false" tabindex="0">
		<span class="menu__btn-title" tabindex="-1">Menu</span>
	</button>
	<ul class="menu__list">
	  
	  <li class="menu__item"><a class="menu__link" href="/"><span class="menu__text">HOME</span></a></li>
	  
		<li class="menu__item">
			<a class="menu__link" href="/about/">
				
				<span class="menu__text">About Me</span>
				
			</a>
		</li>
		<li class="menu__item">
			<a class="menu__link" href="/resources/">
				
				<span class="menu__text">Reference</span>
				
			</a>
		</li>
	</ul>
</nav>

	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">R Time Series Objects vs Data Frames: Advantages and Limitations</h1>
			<div class="post__meta meta">
<div class="meta__item-datetime meta__item">
	<svg class="meta__icon icon icon-time" width="16" height="14" viewBox="0 0 30 28"><path d="M15 0C7 0 1 6 1 14s6 14 14 14 14-6 14-14S23 0 15 0zm0 25C9 25 4 20 4 14S9 3 15 3s11 5 11 11-5 11-11 11zm1-18h-2v8.4l6.8 4.4L22 18l-6-3.8V7z"/></svg><time class="meta__text" datetime="2022-01-30T00:00:00Z">January 30, 2022</time></div><div class="meta__item-categories meta__item"><svg class="meta__icon icon icon-category" width="16" height="16" viewBox="0 0 16 16"><path d="m7 2l1 2h8v11h-16v-13z"/></svg><span class="meta__text"><a class="meta__link" href="/categories/r/" rel="category">R</a>
	</span>
</div></div>
		</header>
		
	<figure class="post__thumbnail thumbnail">
		
		<img class="thumbnail__image" src="/img/time-series-thumb.png" alt="R Time Series Objects vs Data Frames: Advantages and Limitations">
		
	</figure><div class="content post__content clearfix">
			
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/header-attrs/header-attrs.js"></script>
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/htmlwidgets/htmlwidgets.js"></script>
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/jquery/jquery.min.js"></script>
<link href="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/dygraphs/dygraph.css" rel="stylesheet" />
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/dygraphs/dygraph-combined.js"></script>
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/dygraphs/shapes.js"></script>
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/moment/moment.js"></script>
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/moment-timezone/moment-timezone-with-data.js"></script>
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/moment-fquarter/moment-fquarter.min.js"></script>
<script src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/dygraphs-binding/dygraphs.js"></script>

<div id="TOC">
<ul>
<li><a href="#time-series-essentials">Time Series Essentials</a></li>
<li><a href="#time-series-strengths">Time Series Strengths</a></li>
<li><a href="#time-series-manipulationcalculation">Time Series Manipulation/Calculation</a></li>
<li><a href="#visualization">Visualization</a></li>
<li><a href="#decomposition-plots">Decomposition Plots</a></li>
<li><a href="#forecasting">Forecasting</a></li>
<li><a href="#conclusion">Conclusion</a></li>
<li><a href="#resources">Resources</a></li>
</ul>
</div>

<p>As I learn more and more about R, questions often arise about which packages/methods/tools to use for a given situation. R is a vast - and growing - universe and I’m not interested in learning <em>everything</em> in that universe. I’m interested in learning the shortest paths between where I am now and my objective. As an adherent of the tidyverse, I lean strongly toward solutions in that realm. But, to paraphrase an old saying, ‘tidyverse is a playgound…not a jail’ and if a problem can be handled better by stepping outside the tidyverse, I’m all for that.</p>
<p>One of these areas is in dealing with <strong>time series</strong>: data sets comprised of repeated measurements over consistent time intervals (hourly, daily, monthly, etc). You can work with time series data using data frames, the fundamental building block of data analysis in R, but there are more specialized tools that offer more flexibility, specific capabilities and ease of use when analyzing time-based data. This can come into play in a wide variety of situations: weekly website visits, monthly sales, daily stock prices, annual GDP, electricity use by minute, that kind of thing.</p>
<p>So what are these <strong>time series advantages</strong>? How do we leverage them? What limitations of time series objects are good to be aware of? I’m not pretending this is a definitive guide, but I’ve been looking at this for a while and hear are my observations…</p>
<p><em>(A word on forecasting: this is a MAJOR use case for time series but is not the main focus here and I’ll only touch on that briefly below.)</em></p>
<div id="time-series-essentials" class="section level3">
<h3>Time Series Essentials</h3>
<p><strong>ts</strong> is the basic class for time series objects in R. You can do a lot with ts but its functionality have been extend by other packages, in particular <strong>zoo</strong> and more recently <strong>xts</strong>.</p>
<p><strong>xts</strong> is a leading, evolved R package for working with time series. It builds on <strong>zoo</strong>, an earlier pkg for handling time series in R. <strong>Datacamp</strong> has a very nice</p>
<p>So I’m just going to scratch the surface and hit some highlights with examples here.</p>
<div id="get-a-time-series-object" class="section level4">
<h4>Get a Time Series Object</h4>
<p>At its most basic, a time series object is a list or sometimes matrix of observations at regular time intervals.</p>
<p>Examples in built-in R data sets include:</p>
<ul>
<li>annual Nile river flows</li>
</ul>
<pre class="r"><code>class(Nile)</code></pre>
<pre><code>## [1] &quot;ts&quot;</code></pre>
<pre class="r"><code>str(Nile)</code></pre>
<pre><code>##  Time-Series [1:100] from 1871 to 1970: 1120 1160 963 1210 1160 1160 813 1230 1370 1140 ...</code></pre>
<pre class="r"><code>Nile</code></pre>
<pre><code>## Time Series:
## Start = 1871 
## End = 1970 
## Frequency = 1 
##   [1] 1120 1160  963 1210 1160 1160  813 1230 1370 1140  995  935 1110  994 1020
##  [16]  960 1180  799  958 1140 1100 1210 1150 1250 1260 1220 1030 1100  774  840
##  [31]  874  694  940  833  701  916  692 1020 1050  969  831  726  456  824  702
##  [46] 1120 1100  832  764  821  768  845  864  862  698  845  744  796 1040  759
##  [61]  781  865  845  944  984  897  822 1010  771  676  649  846  812  742  801
##  [76] 1040  860  874  848  890  744  749  838 1050  918  986  797  923  975  815
##  [91] 1020  906  901 1170  912  746  919  718  714  740</code></pre>
<ul>
<li>monthly Air Passengers - yes, I know everybody uses Air Passengers for their time series example. So damn handy. Different examples below, I promise. ;)</li>
</ul>
<pre class="r"><code>class(AirPassengers)</code></pre>
<pre><code>## [1] &quot;ts&quot;</code></pre>
<pre class="r"><code>str(AirPassengers)</code></pre>
<pre><code>##  Time-Series [1:144] from 1949 to 1961: 112 118 132 129 121 135 148 148 136 119 ...</code></pre>
<pre class="r"><code>AirPassengers</code></pre>
<pre><code>##      Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
## 1949 112 118 132 129 121 135 148 148 136 119 104 118
## 1950 115 126 141 135 125 149 170 170 158 133 114 140
## 1951 145 150 178 163 172 178 199 199 184 162 146 166
## 1952 171 180 193 181 183 218 230 242 209 191 172 194
## 1953 196 196 236 235 229 243 264 272 237 211 180 201
## 1954 204 188 235 227 234 264 302 293 259 229 203 229
## 1955 242 233 267 269 270 315 364 347 312 274 237 278
## 1956 284 277 317 313 318 374 413 405 355 306 271 306
## 1957 315 301 356 348 355 422 465 467 404 347 305 336
## 1958 340 318 362 348 363 435 491 505 404 359 310 337
## 1959 360 342 406 396 420 472 548 559 463 407 362 405
## 1960 417 391 419 461 472 535 622 606 508 461 390 432</code></pre>
<p>Both these examples are time series of the <strong>ts</strong> class, and we can see right off that these are different data structures from data frames. A key thing to note about time series is that <strong>date/time is not in a column the way it would be in a data frame, but is in an index</strong> - similar to row.names in a data frame.</p>
<p>If we look at the index for the Nile river data, we can see the time values and we can check the start and end. This info corresponds to the structure info shown above, where <strong>start = 1871</strong>, <strong>end = 1970</strong>, and <strong>frequency = 1</strong>, meaning 1 observation per year, <strong>annual data</strong>.</p>
<pre class="r"><code>index(Nile)</code></pre>
<pre><code>##   [1] 1871 1872 1873 1874 1875 1876 1877 1878 1879 1880 1881 1882 1883 1884 1885
##  [16] 1886 1887 1888 1889 1890 1891 1892 1893 1894 1895 1896 1897 1898 1899 1900
##  [31] 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915
##  [46] 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930
##  [61] 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945
##  [76] 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960
##  [91] 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970</code></pre>
<pre class="r"><code>start(Nile)</code></pre>
<pre><code>## [1] 1871    1</code></pre>
<pre class="r"><code>end(Nile)</code></pre>
<pre><code>## [1] 1970    1</code></pre>
<p>As discussed above, ts is useful, but xts offers additional flexibility and features.</p>
</div>
<div id="convert-ts-to-xts" class="section level4">
<h4>Convert ts to xts</h4>
<p>Converting to an xts object can often make the data more intuitive to deal with.</p>
<pre class="r"><code>library(xts)
Nile_xts &lt;- as.xts(Nile)
str(Nile_xts)</code></pre>
<pre><code>## An &#39;xts&#39; object on 1871-01-01/1970-01-01 containing:
##   Data: num [1:100, 1] 1120 1160 963 1210 1160 1160 813 1230 1370 1140 ...
##   Indexed by objects of class: [Date] TZ: UTC
##   xts Attributes:  
##  NULL</code></pre>
<pre class="r"><code>head(Nile_xts)</code></pre>
<pre><code>##            [,1]
## 1871-01-01 1120
## 1872-01-01 1160
## 1873-01-01  963
## 1874-01-01 1210
## 1875-01-01 1160
## 1876-01-01 1160</code></pre>
<pre class="r"><code>Air_xts &lt;- as.xts(AirPassengers)
str(Air_xts)</code></pre>
<pre><code>## An &#39;xts&#39; object on Jan 1949/Dec 1960 containing:
##   Data: num [1:144, 1] 112 118 132 129 121 135 148 148 136 119 ...
##   Indexed by objects of class: [yearmon] TZ: UTC
##   xts Attributes:  
##  NULL</code></pre>
<pre class="r"><code>head(Air_xts)</code></pre>
<pre><code>##          [,1]
## Jan 1949  112
## Feb 1949  118
## Mar 1949  132
## Apr 1949  129
## May 1949  121
## Jun 1949  135</code></pre>
<ul>
<li>We can see here that xts has reshaped the data from a matrix with rows by year and columns by month to more ‘tidy’ data with <strong>mth-year as index</strong> and <strong>observations in one column</strong>.</li>
</ul>
</div>
<div id="native-xts" class="section level4">
<h4>Native xts</h4>
<p>Some data comes as <strong>xts time series</strong> out of the box. For example, the <strong>quantmod</strong> package fetches stock market data as xts time series automatically:</p>
<pre class="r"><code>library(quantmod)
## use quantmod pkg to get some stock prices as time series
price &lt;- getSymbols(Symbols=&#39;EA&#39;, from=&quot;2020-01-01&quot;, to=Sys.Date(), auto.assign=FALSE)
class(price)</code></pre>
<pre><code>## [1] &quot;xts&quot; &quot;zoo&quot;</code></pre>
<pre class="r"><code>head(price)</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2020-01-02     108     108    107      107   1901000         107
## 2020-01-03     106     108    105      107   1840300         107
## 2020-01-06     107     109    107      109   2934200         108
## 2020-01-07     109     109    108      108   1692400         108
## 2020-01-08     108     110    108      109   2651600         109
## 2020-01-09     110     110    108      109   1818600         109</code></pre>
<p>As noted, a key characteristic of time series object is that <strong>dates are in an index</strong> rather than being in a date column, as they would be in typical data frame. Looking at the structure of the xts object, we can again see it is different from a data frame.</p>
<pre class="r"><code>str(price)</code></pre>
<pre><code>## An &#39;xts&#39; object on 2020-01-02/2022-01-28 containing:
##   Data: num [1:524, 1:6] 108 106 107 109 108 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : NULL
##   ..$ : chr [1:6] &quot;EA.Open&quot; &quot;EA.High&quot; &quot;EA.Low&quot; &quot;EA.Close&quot; ...
##   Indexed by objects of class: [Date] TZ: UTC
##   xts Attributes:  
## List of 2
##  $ src    : chr &quot;yahoo&quot;
##  $ updated: POSIXct[1:1], format: &quot;2022-01-30 17:27:51&quot;</code></pre>
</div>
<div id="convert-xts-to-data-frame" class="section level4">
<h4>Convert xts to data frame</h4>
<p>If you want to work with the time series as a data frame, it is fairly straightforward to convert an xts object:</p>
<pre class="r"><code>price_df &lt;- as.data.frame(price)
## add Date field based on index (row names) of xts object
price_df$Date &lt;- index(price)
## set data frame row names to numbers instead of dates
rownames(price_df) &lt;- seq(1:nrow(price))
## reorder columns to put Date first
price_df &lt;- price_df %&gt;% select(Date, 1:ncol(price_df)-1)
## check out structure using glimpse, as is the fashion of the times
glimpse(price_df)</code></pre>
<pre><code>## Rows: 524
## Columns: 7
## $ Date        &lt;date&gt; 2020-01-02, 2020-01-03, 2020-01-06, 2020-01-07, 2020-01-0…
## $ EA.Open     &lt;dbl&gt; 108, 106, 107, 109, 108, 110, 109, 109, 110, 110, 110, 112…
## $ EA.High     &lt;dbl&gt; 108, 108, 109, 109, 110, 110, 109, 110, 110, 110, 111, 113…
## $ EA.Low      &lt;dbl&gt; 107, 105, 107, 108, 108, 108, 108, 109, 109, 109, 110, 112…
## $ EA.Close    &lt;dbl&gt; 107, 107, 109, 108, 109, 109, 109, 110, 110, 110, 111, 113…
## $ EA.Volume   &lt;dbl&gt; 1901000, 1840300, 2934200, 1692400, 2651600, 1818600, 1756…
## $ EA.Adjusted &lt;dbl&gt; 107, 107, 108, 108, 109, 109, 108, 109, 109, 109, 111, 112…</code></pre>
<p>Data frame is basically a straight-up table, whereas the xts object has other structural features.</p>
</div>
<div id="convert-data-frame-to-xts" class="section level4">
<h4>Convert data frame to xts</h4>
<pre class="r"><code>## convert data frame to xts object by specifying the date field to use for xts index.
price_xts &lt;- xts(price_df, order.by=as.Date(price_df$Date))
str(price_xts)</code></pre>
<pre><code>## An &#39;xts&#39; object on 2020-01-02/2022-01-28 containing:
##   Data: chr [1:524, 1:7] &quot;2020-01-02&quot; &quot;2020-01-03&quot; &quot;2020-01-06&quot; &quot;2020-01-07&quot; ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : NULL
##   ..$ : chr [1:7] &quot;Date&quot; &quot;EA.Open&quot; &quot;EA.High&quot; &quot;EA.Low&quot; ...
##   Indexed by objects of class: [Date] TZ: UTC
##   xts Attributes:  
##  NULL</code></pre>
<p>Notice, however, that in the process of converting an xts object to data frame and back to xts, the xts Attributes information has been lost.</p>
</div>
<div id="savingexporting-time-series-data" class="section level4">
<h4>Saving/Exporting time series data</h4>
<p>Due to the structure of an xts object, the best way to save/export for future use in R and preserve all its attributes is to save as <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/readRDS">RDS file</a>, using <strong>saveRDS</strong>. (additional helpful RDS info <a href="https://rstudio-education.github.io/hopr/dataio.html#r-files">here</a>.)</p>
<p>However, this won’t be helpful if you need to share the data with someone who is not using R. You can save as a CSV file using <strong>write.zoo</strong> (be sure to specificy sep=“,”) and this will maintain the table structure of the data but will drop the attributes. It will automatically move the indexes into an Index column so if someone opens it in Excel/Google Sheets, they will see the dates/times.</p>
<p>Saving as RDS or CSV:</p>
<pre class="r"><code>## save as RDS to preserve attributes
saveRDS(price, file=&quot;price.rds&quot;)
price_rds &lt;- readRDS(file=&#39;price.rds&#39;)
str(price_rds)</code></pre>
<pre><code>## An &#39;xts&#39; object on 2020-01-02/2022-01-28 containing:
##   Data: num [1:524, 1:6] 108 106 107 109 108 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : NULL
##   ..$ : chr [1:6] &quot;EA.Open&quot; &quot;EA.High&quot; &quot;EA.Low&quot; &quot;EA.Close&quot; ...
##   Indexed by objects of class: [Date] TZ: UTC
##   xts Attributes:  
## List of 2
##  $ src    : chr &quot;yahoo&quot;
##  $ updated: POSIXct[1:1], format: &quot;2022-01-30 17:27:51&quot;</code></pre>
<pre class="r"><code>## save as CSV - ensure to include sep=&quot;,&quot;
write.zoo(price, file=&#39;price.csv&#39;, sep=&quot;,&quot;)
price_zoo &lt;- read_csv(&#39;price.csv&#39;)</code></pre>
</div>
</div>
<div id="time-series-strengths" class="section level3">
<h3>Time Series Strengths</h3>
<p>The structure of a time series leads a variety of advantages related to time-based analysis, compared to data frames. A few of the main ones, at least from my perspective:</p>
<ul>
<li><strong>Period/Frequency Manipulation</strong>: can easily change from granular periods, such as daily, to aggregated periods.</li>
<li><strong>Period calculations</strong>: counting number of periods in the data (months, quarters, years).</li>
<li><strong>Selection/subsetting</strong> based on date ranges.</li>
<li><strong>Visualization</strong>: a number of visualization options are designed to work with time series.</li>
<li><strong>Decomposition</strong>: breaking out time series into trend, seasonal, random components for analysis.</li>
<li><strong>Forecasting</strong>: time series objects are designed for applying various forecasting methods like Holt-Winters and ARIMA. This is well beyond the scope of this post, but we’ll show a quick ARIMA example.</li>
</ul>
<p>No doubt everything you can do with time series can be done with data frames, but using a time series object can really expedite things.</p>
</div>
<div id="time-series-manipulationcalculation" class="section level3">
<h3>Time Series Manipulation/Calculation</h3>
<div id="periodfrequency-manipulation" class="section level4">
<h4>Period/Frequency Manipulation</h4>
<p>Change the period granularity to less granular:</p>
<ul>
<li>easily change daily data to weekly, monthly, quarterly, yearly</li>
</ul>
<pre class="r"><code>## get periodicity (frequency) for data set
periodicity(price)</code></pre>
<pre><code>## Daily periodicity from 2020-01-02 to 2022-01-28</code></pre>
<pre class="r"><code>## aggregate by period
head(to.weekly(price)[,1:5])</code></pre>
<pre><code>##            price.Open price.High price.Low price.Close price.Volume
## 2020-01-03        108        108       105         107      3741300
## 2020-01-10        107        110       107         109     10852800
## 2020-01-17        109        113       109         113     10221500
## 2020-01-24        113        114       112         112      8457000
## 2020-01-31        110        113       106         108     18435600
## 2020-02-07        108        111       104         109     15973600</code></pre>
<pre class="r"><code>head(to.monthly(price)[,1:5])</code></pre>
<pre><code>##          price.Open price.High price.Low price.Close price.Volume
## Jan 2020      107.9        114     105.1         108     51708200
## Feb 2020      107.9        111      98.6         101     55140000
## Mar 2020      101.9        112      85.7         100    116497800
## Apr 2020       98.4        119      96.7         114     72981400
## May 2020      113.1        123     111.1         123     71400200
## Jun 2020      123.3        134     113.3         132     64143400</code></pre>
<pre class="r"><code>head(to.yearly(price)[,1:5])</code></pre>
<pre><code>##            price.Open price.High price.Low price.Close price.Volume
## 2020-12-31        108        147      85.7         144    747474600
## 2021-12-31        143        150     120.1         132    641690300
## 2022-01-28        132        143     127.3         132     52621400</code></pre>
<p>Notice that this isn’t a straight roll-up but actual summary: for the monthly data, the High is max of daily data for the month, the Low is minimum for the month, while volume is the sum for the month, all as you would expect.</p>
</div>
<div id="period-counts" class="section level4">
<h4>Period Counts</h4>
<pre class="r"><code>## get the number of weeks, months, years in the dataset (including partial)
price_nw &lt;- nweeks(price)
price_nm &lt;- nmonths(price)
price_ny &lt;- nyears(price)</code></pre>
<p>The price data covers:</p>
<ul>
<li>524 days</li>
<li>109 weeks</li>
<li>25 months</li>
<li>3 years (or <em>portions</em> thereof)</li>
</ul>
<p>First/last dates:</p>
<pre class="r"><code>## get earliest date
st_date &lt;- start(price)
## get last date
end_date &lt;- end(price)</code></pre>
<ul>
<li>Start: 2020-01-02</li>
<li>End: 2022-01-28</li>
</ul>
</div>
<div id="selectingsubsetting" class="section level4">
<h4>Selecting/Subsetting</h4>
<p>Time series objects make it easy to slice the data by date ranges. This is an area where time series <em>really</em> shine compared to trying to do the same thing with a data frame.</p>
<ul>
<li>xts is super-efficient at interpreting date ranges based on minimal info.</li>
<li><strong>‘/’</strong> is a key symbol for separating dates - it is your friend.</li>
<li>date ranges are inclusive of references used.</li>
</ul>
<p>Note that in the following examples based on stock market data, dates are missing due to gaps in data - days when markets closed.</p>
<ul>
<li>quickly get <strong>entire YEAR</strong></li>
</ul>
<pre class="r"><code>## subset on a YEAR (showing head and tail to confirm data is 2021 only)
head(price[&quot;2021&quot;])</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2021-01-04     143     144    138      140   3587000         139
## 2021-01-05     140     141    138      141   2117800         141
## 2021-01-06     139     140    136      137   2398500         136
## 2021-01-07     137     141    137      141   2936200         140
## 2021-01-08     141     142    140      142   1902700         141
## 2021-01-11     142     142    139      141   2589800         141</code></pre>
<pre class="r"><code>tail(price[&quot;2021&quot;])</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2021-12-23     131     133    131      133   1594000         133
## 2021-12-27     133     134    132      133   1377300         133
## 2021-12-28     133     135    133      133   1230700         133
## 2021-12-29     134     134    132      133    912300         133
## 2021-12-30     134     136    134      134   1177000         134
## 2021-12-31     134     135    132      132   1610900         132</code></pre>
<ul>
<li><strong>DURING</strong> selected month</li>
</ul>
<pre class="r"><code>## get data DURING selected month
price[&quot;2020-02&quot;]</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2020-02-03     108     109  104.4      105   4155500         104
## 2020-02-04     106     107  105.3      107   4190500         106
## 2020-02-05     109     109  107.1      108   2895700         107
## 2020-02-06     109     110  108.4      110   2500600         109
## 2020-02-07     109     111  108.7      109   2231300         108
## 2020-02-10     109     110  108.2      109   2170800         108
## 2020-02-11     109     109  107.9      109   1195300         108
## 2020-02-12     110     110  108.6      110   1567200         109
## 2020-02-13     109     109  108.0      109   1627000         108
## 2020-02-14     109     110  108.8      110   1227500         109
## 2020-02-18     109     110  108.7      109   2171400         109
## 2020-02-19     110     111  109.4      110   1540000         109
## 2020-02-20     109     109  107.4      109   4034000         109
## 2020-02-21     108     109  106.8      108   2546900         107
## 2020-02-24     105     108  105.0      107   2817100         106
## 2020-02-25     108     109  105.2      105   3651300         105
## 2020-02-26     106     108  105.6      107   2858000         106
## 2020-02-27     104     106  102.7      103   4906200         102
## 2020-02-28     100     102   98.6      101   6853700         101</code></pre>
<ul>
<li><strong>FROM</strong> start of year to <strong>END OF SPECIFIC MONTH</strong></li>
</ul>
<pre class="r"><code>## get data FROM start of a year to END OF SPECIFIC MONTH
price_jf &lt;- price[&quot;2021/2021-02&quot;]
head(price_jf, 4)</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2021-01-04     143     144    138      140   3587000         139
## 2021-01-05     140     141    138      141   2117800         141
## 2021-01-06     139     140    136      137   2398500         136
## 2021-01-07     137     141    137      141   2936200         140</code></pre>
<pre class="r"><code>tail(price_jf, 3)</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2021-02-24     138     140    137      138   3735500         137
## 2021-02-25     137     139    134      135   3042600         135
## 2021-02-26     136     138    134      134   3646600         133</code></pre>
<ul>
<li>everything <strong>BEFORE</strong> specified date</li>
</ul>
<pre class="r"><code>## get everything BEFORE specified date (based on what is avaliable)
price[&quot;/2020-01-06&quot;]</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2020-01-02     108     108    107      107   1901000         107
## 2020-01-03     106     108    105      107   1840300         107
## 2020-01-06     107     109    107      109   2934200         108</code></pre>
<ul>
<li>everything <strong>BETWEEN</strong> two dates</li>
</ul>
<pre class="r"><code>## get everything BETWEEN two dates
price[&quot;2021-06-01/2021-06-04&quot;]</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2021-06-01     142     144    142      144   2610300         143
## 2021-06-02     144     144    141      141   1522100         141
## 2021-06-03     141     143    141      142   1574900         142
## 2021-06-04     143     146    143      145   1919500         145</code></pre>
<ul>
<li>everything <strong>AFTER</strong> specified date</li>
</ul>
<pre class="r"><code>## get everything AFTER specified date
price[&quot;2022-01-18/&quot;]</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2022-01-18     138     143    133      134   8758900         134
## 2022-01-19     136     138    135      137   3820300         137
## 2022-01-20     138     142    138      139   3116900         139
## 2022-01-21     138     141    138      139   3119400         139
## 2022-01-24     137     139    132      135   4262100         135
## 2022-01-25     134     134    130      131   2386400         131
## 2022-01-26     131     132    129      130   2333800         130
## 2022-01-27     131     134    131      131   1781500         131
## 2022-01-28     131     132    130      132   2154300         132</code></pre>
</div>
<div id="period-calculations" class="section level4">
<h4>Period Calculations</h4>
<p>Time series objects lend themselves well to time-based calculations.</p>
<p>Simple arithmetic between two dates is not as straightforward as might be expected, but still easily doable:</p>
<pre class="r"><code>## subtraction of a given metric between two dates
as.numeric(price$EA.Close[&quot;2022-01-21&quot;])-as.numeric(price$EA.Close[&quot;2022-01-18&quot;])</code></pre>
<pre><code>## [1] 5.1</code></pre>
<pre class="r"><code>## subtraction of one metric from another on same date
price$EA.Close[&quot;2022-01-18&quot;]-price$EA.Open[&quot;2022-01-18&quot;]</code></pre>
<pre><code>##            EA.Close
## 2022-01-18    -4.53</code></pre>
<p><strong>Lag.xts</strong> is versatile for lag calculations, calculating differences over time:</p>
<pre class="r"><code>## calculates across all columns with one command - default is 1 period but can be set with k
head(price-lag.xts(price))</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2020-01-02      NA      NA     NA       NA        NA          NA
## 2020-01-03   -2.36   -0.60  -1.64    -0.14    -60700      -0.139
## 2020-01-06    1.37    1.56   1.51     1.58   1093900       1.570
## 2020-01-07    2.05   -0.06   1.10    -0.39  -1241800      -0.388
## 2020-01-08   -0.82    0.75   0.05     1.10    959200       1.093
## 2020-01-09    1.82    0.34   0.49    -0.13   -833000      -0.129</code></pre>
<pre class="r"><code>## set k for longer lag - this example starting at a date beyond available data for the lag calculations, so no NAs
head(price[&quot;2020-01-13/&quot;]-lag.xts(price, k=7))</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2020-01-13    1.11    1.72   1.86     2.48    -43600       2.464
## 2020-01-14    4.08    2.42   3.59     2.38   -116900       2.365
## 2020-01-15    2.84    1.14   2.51     0.83  -1455100       0.825
## 2020-01-16    1.00    2.04   2.22     2.87    415900       2.852
## 2020-01-17    4.19    2.99   3.77     3.44    401700       3.418
## 2020-01-21    2.55    2.63   3.50     3.05    346400       3.031</code></pre>
<pre class="r"><code>## works for individual column
price$EA.Close[&quot;2022-01-18/&quot;]-lag.xts(price$EA.Close, k=2)</code></pre>
<pre><code>##            EA.Close
## 2022-01-18     3.07
## 2022-01-19     6.47
## 2022-01-20     4.97
## 2022-01-21     2.10
## 2022-01-24    -3.68
## 2022-01-25    -8.00
## 2022-01-26    -5.22
## 2022-01-27     0.05
## 2022-01-28     1.94</code></pre>
<p><strong>Diff</strong> for calculating differences, based on combination of lag and difference order:</p>
<pre class="r"><code>head(diff(price, lag=1, differences=1))</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2020-01-02      NA      NA     NA       NA        NA          NA
## 2020-01-03   -2.36   -0.60  -1.64    -0.14    -60700      -0.139
## 2020-01-06    1.37    1.56   1.51     1.58   1093900       1.570
## 2020-01-07    2.05   -0.06   1.10    -0.39  -1241800      -0.388
## 2020-01-08   -0.82    0.75   0.05     1.10    959200       1.093
## 2020-01-09    1.82    0.34   0.49    -0.13   -833000      -0.129</code></pre>
<pre class="r"><code>head(diff(price, lag=1, differences=2))</code></pre>
<pre><code>##            EA.Open EA.High EA.Low EA.Close EA.Volume EA.Adjusted
## 2020-01-02      NA      NA     NA       NA        NA          NA
## 2020-01-03      NA      NA     NA       NA        NA          NA
## 2020-01-06    3.73    2.16   3.15     1.72   1154600        1.71
## 2020-01-07    0.68   -1.62  -0.41    -1.97  -2335700       -1.96
## 2020-01-08   -2.87    0.81  -1.05     1.49   2201000        1.48
## 2020-01-09    2.64   -0.41   0.44    -1.23  -1792200       -1.22</code></pre>
<ul>
<li>first example: diff with lag=1, differences=1 gives same result as lag.xts with k=1 (or default)</li>
<li>second example: diff with differences=2 gives the ‘second order difference’: difference between the differences.
<ul>
<li>EA.Open:
<ul>
<li>3.73 = 1.37-(-2.36)</li>
<li>0.68 = 2.05-1.37</li>
<li>-2.87 = -0.82-2.05</li>
<li>…</li>
</ul></li>
</ul></li>
</ul>
<p>Useful for some forecasting methods, among other applications.</p>
<p><strong>Returns</strong> for calculating % change period over period:</p>
<ul>
<li>functions in <strong>quantmod</strong> package designed for financial asset prices, but can be applied to other xts data.</li>
<li>various periodicity: daily, weekly, monthly, quarterly, yearly or ALL at once (allReturn())</li>
</ul>
<pre class="r"><code>head(dailyReturn(price))</code></pre>
<pre><code>##            daily.returns
## 2020-01-02      -0.00556
## 2020-01-03      -0.00130
## 2020-01-06       0.01474
## 2020-01-07      -0.00359
## 2020-01-08       0.01015
## 2020-01-09      -0.00119</code></pre>
<pre class="r"><code>head(monthlyReturn(price))</code></pre>
<pre><code>##            monthly.returns
## 2020-01-31       -0.000185
## 2020-02-28       -0.060693
## 2020-03-31       -0.011838
## 2020-04-30        0.140661
## 2020-05-29        0.075442
## 2020-06-30        0.074626</code></pre>
<ul>
<li>applied to Air Passenger xts to get % change, even though not financial returns:</li>
</ul>
<pre class="r"><code>head(monthlyReturn(Air_xts))</code></pre>
<pre><code>##          monthly.returns
## Jan 1949          0.0000
## Feb 1949          0.0536
## Mar 1949          0.1186
## Apr 1949         -0.0227
## May 1949         -0.0620
## Jun 1949          0.1157</code></pre>
</div>
</div>
<div id="visualization" class="section level3">
<h3>Visualization</h3>
<p>Time series objects offer some different visualization opportunities than data frames. Below are a couple of options.</p>
<div id="plot.ts" class="section level4">
<h4>Plot.ts</h4>
<p>You can do a quick, simple plot with plot.ts(). Note that in this case the x-axis is the numerical index of the data point, and doesn’t show the date.</p>
<pre class="r"><code>plot.ts(price$EA.Close)</code></pre>
<p><img src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/figure-html/unnamed-chunk-25-1.png" width="768" /></p>
</div>
<div id="dygraphs" class="section level4">
<h4>Dygraphs</h4>
<p>The <strong>dygraphs package</strong> offers flexibility and <strong>interactivity</strong> for time series.</p>
<ul>
<li>easily show multiple metrics at once.</li>
<li><strong>scroll over</strong> to see details.</li>
<li><strong>select chart area</strong> to zoom in.</li>
</ul>
<pre class="r"><code>library(dygraphs)
dygraph(price[,1:4])</code></pre>
<div id="htmlwidget-1" style="width:768px;height:384px;" class="dygraphs html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"attrs":{"labels":["day","EA.Open","EA.High","EA.Low","EA.Close"],"legend":"auto","retainDateWindow":false,"axes":{"x":{"pixelsPerLabel":60}}},"scale":"daily","annotations":[],"shadings":[],"events":[],"format":"date","data":[["2020-01-02T00:00:00.000Z","2020-01-03T00:00:00.000Z","2020-01-06T00:00:00.000Z","2020-01-07T00:00:00.000Z","2020-01-08T00:00:00.000Z","2020-01-09T00:00:00.000Z","2020-01-10T00:00:00.000Z","2020-01-13T00:00:00.000Z","2020-01-14T00:00:00.000Z","2020-01-15T00:00:00.000Z","2020-01-16T00:00:00.000Z","2020-01-17T00:00:00.000Z","2020-01-21T00:00:00.000Z","2020-01-22T00:00:00.000Z","2020-01-23T00:00:00.000Z","2020-01-24T00:00:00.000Z","2020-01-27T00:00:00.000Z","2020-01-28T00:00:00.000Z","2020-01-29T00:00:00.000Z","2020-01-30T00:00:00.000Z","2020-01-31T00:00:00.000Z","2020-02-03T00:00:00.000Z","2020-02-04T00:00:00.000Z","2020-02-05T00:00:00.000Z","2020-02-06T00:00:00.000Z","2020-02-07T00:00:00.000Z","2020-02-10T00:00:00.000Z","2020-02-11T00:00:00.000Z","2020-02-12T00:00:00.000Z","2020-02-13T00:00:00.000Z","2020-02-14T00:00:00.000Z","2020-02-18T00:00:00.000Z","2020-02-19T00:00:00.000Z","2020-02-20T00:00:00.000Z","2020-02-21T00:00:00.000Z","2020-02-24T00:00:00.000Z","2020-02-25T00:00:00.000Z","2020-02-26T00:00:00.000Z","2020-02-27T00:00:00.000Z","2020-02-28T00:00:00.000Z","2020-03-02T00:00:00.000Z","2020-03-03T00:00:00.000Z","2020-03-04T00:00:00.000Z","2020-03-05T00:00:00.000Z","2020-03-06T00:00:00.000Z","2020-03-09T00:00:00.000Z","2020-03-10T00:00:00.000Z","2020-03-11T00:00:00.000Z","2020-03-12T00:00:00.000Z","2020-03-13T00:00:00.000Z","2020-03-16T00:00:00.000Z","2020-03-17T00:00:00.000Z","2020-03-18T00:00:00.000Z","2020-03-19T00:00:00.000Z","2020-03-20T00:00:00.000Z","2020-03-23T00:00:00.000Z","2020-03-24T00:00:00.000Z","2020-03-25T00:00:00.000Z","2020-03-26T00:00:00.000Z","2020-03-27T00:00:00.000Z","2020-03-30T00:00:00.000Z","2020-03-31T00:00:00.000Z","2020-04-01T00:00:00.000Z","2020-04-02T00:00:00.000Z","2020-04-03T00:00:00.000Z","2020-04-06T00:00:00.000Z","2020-04-07T00:00:00.000Z","2020-04-08T00:00:00.000Z","2020-04-09T00:00:00.000Z","2020-04-13T00:00:00.000Z","2020-04-14T00:00:00.000Z","2020-04-15T00:00:00.000Z","2020-04-16T00:00:00.000Z","2020-04-17T00:00:00.000Z","2020-04-20T00:00:00.000Z","2020-04-21T00:00:00.000Z","2020-04-22T00:00:00.000Z","2020-04-23T00:00:00.000Z","2020-04-24T00:00:00.000Z","2020-04-27T00:00:00.000Z","2020-04-28T00:00:00.000Z","2020-04-29T00:00:00.000Z","2020-04-30T00:00:00.000Z","2020-05-01T00:00:00.000Z","2020-05-04T00:00:00.000Z","2020-05-05T00:00:00.000Z","2020-05-06T00:00:00.000Z","2020-05-07T00:00:00.000Z","2020-05-08T00:00:00.000Z","2020-05-11T00:00:00.000Z","2020-05-12T00:00:00.000Z","2020-05-13T00:00:00.000Z","2020-05-14T00:00:00.000Z","2020-05-15T00:00:00.000Z","2020-05-18T00:00:00.000Z","2020-05-19T00:00:00.000Z","2020-05-20T00:00:00.000Z","2020-05-21T00:00:00.000Z","2020-05-22T00:00:00.000Z","2020-05-26T00:00:00.000Z","2020-05-27T00:00:00.000Z","2020-05-28T00:00:00.000Z","2020-05-29T00:00:00.000Z","2020-06-01T00:00:00.000Z","2020-06-02T00:00:00.000Z","2020-06-03T00:00:00.000Z","2020-06-04T00:00:00.000Z","2020-06-05T00:00:00.000Z","2020-06-08T00:00:00.000Z","2020-06-09T00:00:00.000Z","2020-06-10T00:00:00.000Z","2020-06-11T00:00:00.000Z","2020-06-12T00:00:00.000Z","2020-06-15T00:00:00.000Z","2020-06-16T00:00:00.000Z","2020-06-17T00:00:00.000Z","2020-06-18T00:00:00.000Z","2020-06-19T00:00:00.000Z","2020-06-22T00:00:00.000Z","2020-06-23T00:00:00.000Z","2020-06-24T00:00:00.000Z","2020-06-25T00:00:00.000Z","2020-06-26T00:00:00.000Z","2020-06-29T00:00:00.000Z","2020-06-30T00:00:00.000Z","2020-07-01T00:00:00.000Z","2020-07-02T00:00:00.000Z","2020-07-06T00:00:00.000Z","2020-07-07T00:00:00.000Z","2020-07-08T00:00:00.000Z","2020-07-09T00:00:00.000Z","2020-07-10T00:00:00.000Z","2020-07-13T00:00:00.000Z","2020-07-14T00:00:00.000Z","2020-07-15T00:00:00.000Z","2020-07-16T00:00:00.000Z","2020-07-17T00:00:00.000Z","2020-07-20T00:00:00.000Z","2020-07-21T00:00:00.000Z","2020-07-22T00:00:00.000Z","2020-07-23T00:00:00.000Z","2020-07-24T00:00:00.000Z","2020-07-27T00:00:00.000Z","2020-07-28T00:00:00.000Z","2020-07-29T00:00:00.000Z","2020-07-30T00:00:00.000Z","2020-07-31T00:00:00.000Z","2020-08-03T00:00:00.000Z","2020-08-04T00:00:00.000Z","2020-08-05T00:00:00.000Z","2020-08-06T00:00:00.000Z","2020-08-07T00:00:00.000Z","2020-08-10T00:00:00.000Z","2020-08-11T00:00:00.000Z","2020-08-12T00:00:00.000Z","2020-08-13T00:00:00.000Z","2020-08-14T00:00:00.000Z","2020-08-17T00:00:00.000Z","2020-08-18T00:00:00.000Z","2020-08-19T00:00:00.000Z","2020-08-20T00:00:00.000Z","2020-08-21T00:00:00.000Z","2020-08-24T00:00:00.000Z","2020-08-25T00:00:00.000Z","2020-08-26T00:00:00.000Z","2020-08-27T00:00:00.000Z","2020-08-28T00:00:00.000Z","2020-08-31T00:00:00.000Z","2020-09-01T00:00:00.000Z","2020-09-02T00:00:00.000Z","2020-09-03T00:00:00.000Z","2020-09-04T00:00:00.000Z","2020-09-08T00:00:00.000Z","2020-09-09T00:00:00.000Z","2020-09-10T00:00:00.000Z","2020-09-11T00:00:00.000Z","2020-09-14T00:00:00.000Z","2020-09-15T00:00:00.000Z","2020-09-16T00:00:00.000Z","2020-09-17T00:00:00.000Z","2020-09-18T00:00:00.000Z","2020-09-21T00:00:00.000Z","2020-09-22T00:00:00.000Z","2020-09-23T00:00:00.000Z","2020-09-24T00:00:00.000Z","2020-09-25T00:00:00.000Z","2020-09-28T00:00:00.000Z","2020-09-29T00:00:00.000Z","2020-09-30T00:00:00.000Z","2020-10-01T00:00:00.000Z","2020-10-02T00:00:00.000Z","2020-10-05T00:00:00.000Z","2020-10-06T00:00:00.000Z","2020-10-07T00:00:00.000Z","2020-10-08T00:00:00.000Z","2020-10-09T00:00:00.000Z","2020-10-12T00:00:00.000Z","2020-10-13T00:00:00.000Z","2020-10-14T00:00:00.000Z","2020-10-15T00:00:00.000Z","2020-10-16T00:00:00.000Z","2020-10-19T00:00:00.000Z","2020-10-20T00:00:00.000Z","2020-10-21T00:00:00.000Z","2020-10-22T00:00:00.000Z","2020-10-23T00:00:00.000Z","2020-10-26T00:00:00.000Z","2020-10-27T00:00:00.000Z","2020-10-28T00:00:00.000Z","2020-10-29T00:00:00.000Z","2020-10-30T00:00:00.000Z","2020-11-02T00:00:00.000Z","2020-11-03T00:00:00.000Z","2020-11-04T00:00:00.000Z","2020-11-05T00:00:00.000Z","2020-11-06T00:00:00.000Z","2020-11-09T00:00:00.000Z","2020-11-10T00:00:00.000Z","2020-11-11T00:00:00.000Z","2020-11-12T00:00:00.000Z","2020-11-13T00:00:00.000Z","2020-11-16T00:00:00.000Z","2020-11-17T00:00:00.000Z","2020-11-18T00:00:00.000Z","2020-11-19T00:00:00.000Z","2020-11-20T00:00:00.000Z","2020-11-23T00:00:00.000Z","2020-11-24T00:00:00.000Z","2020-11-25T00:00:00.000Z","2020-11-27T00:00:00.000Z","2020-11-30T00:00:00.000Z","2020-12-01T00:00:00.000Z","2020-12-02T00:00:00.000Z","2020-12-03T00:00:00.000Z","2020-12-04T00:00:00.000Z","2020-12-07T00:00:00.000Z","2020-12-08T00:00:00.000Z","2020-12-09T00:00:00.000Z","2020-12-10T00:00:00.000Z","2020-12-11T00:00:00.000Z","2020-12-14T00:00:00.000Z","2020-12-15T00:00:00.000Z","2020-12-16T00:00:00.000Z","2020-12-17T00:00:00.000Z","2020-12-18T00:00:00.000Z","2020-12-21T00:00:00.000Z","2020-12-22T00:00:00.000Z","2020-12-23T00:00:00.000Z","2020-12-24T00:00:00.000Z","2020-12-28T00:00:00.000Z","2020-12-29T00:00:00.000Z","2020-12-30T00:00:00.000Z","2020-12-31T00:00:00.000Z","2021-01-04T00:00:00.000Z","2021-01-05T00:00:00.000Z","2021-01-06T00:00:00.000Z","2021-01-07T00:00:00.000Z","2021-01-08T00:00:00.000Z","2021-01-11T00:00:00.000Z","2021-01-12T00:00:00.000Z","2021-01-13T00:00:00.000Z","2021-01-14T00:00:00.000Z","2021-01-15T00:00:00.000Z","2021-01-19T00:00:00.000Z","2021-01-20T00:00:00.000Z","2021-01-21T00:00:00.000Z","2021-01-22T00:00:00.000Z","2021-01-25T00:00:00.000Z","2021-01-26T00:00:00.000Z","2021-01-27T00:00:00.000Z","2021-01-28T00:00:00.000Z","2021-01-29T00:00:00.000Z","2021-02-01T00:00:00.000Z","2021-02-02T00:00:00.000Z","2021-02-03T00:00:00.000Z","2021-02-04T00:00:00.000Z","2021-02-05T00:00:00.000Z","2021-02-08T00:00:00.000Z","2021-02-09T00:00:00.000Z","2021-02-10T00:00:00.000Z","2021-02-11T00:00:00.000Z","2021-02-12T00:00:00.000Z","2021-02-16T00:00:00.000Z","2021-02-17T00:00:00.000Z","2021-02-18T00:00:00.000Z","2021-02-19T00:00:00.000Z","2021-02-22T00:00:00.000Z","2021-02-23T00:00:00.000Z","2021-02-24T00:00:00.000Z","2021-02-25T00:00:00.000Z","2021-02-26T00:00:00.000Z","2021-03-01T00:00:00.000Z","2021-03-02T00:00:00.000Z","2021-03-03T00:00:00.000Z","2021-03-04T00:00:00.000Z","2021-03-05T00:00:00.000Z","2021-03-08T00:00:00.000Z","2021-03-09T00:00:00.000Z","2021-03-10T00:00:00.000Z","2021-03-11T00:00:00.000Z","2021-03-12T00:00:00.000Z","2021-03-15T00:00:00.000Z","2021-03-16T00:00:00.000Z","2021-03-17T00:00:00.000Z","2021-03-18T00:00:00.000Z","2021-03-19T00:00:00.000Z","2021-03-22T00:00:00.000Z","2021-03-23T00:00:00.000Z","2021-03-24T00:00:00.000Z","2021-03-25T00:00:00.000Z","2021-03-26T00:00:00.000Z","2021-03-29T00:00:00.000Z","2021-03-30T00:00:00.000Z","2021-03-31T00:00:00.000Z","2021-04-01T00:00:00.000Z","2021-04-05T00:00:00.000Z","2021-04-06T00:00:00.000Z","2021-04-07T00:00:00.000Z","2021-04-08T00:00:00.000Z","2021-04-09T00:00:00.000Z","2021-04-12T00:00:00.000Z","2021-04-13T00:00:00.000Z","2021-04-14T00:00:00.000Z","2021-04-15T00:00:00.000Z","2021-04-16T00:00:00.000Z","2021-04-19T00:00:00.000Z","2021-04-20T00:00:00.000Z","2021-04-21T00:00:00.000Z","2021-04-22T00:00:00.000Z","2021-04-23T00:00:00.000Z","2021-04-26T00:00:00.000Z","2021-04-27T00:00:00.000Z","2021-04-28T00:00:00.000Z","2021-04-29T00:00:00.000Z","2021-04-30T00:00:00.000Z","2021-05-03T00:00:00.000Z","2021-05-04T00:00:00.000Z","2021-05-05T00:00:00.000Z","2021-05-06T00:00:00.000Z","2021-05-07T00:00:00.000Z","2021-05-10T00:00:00.000Z","2021-05-11T00:00:00.000Z","2021-05-12T00:00:00.000Z","2021-05-13T00:00:00.000Z","2021-05-14T00:00:00.000Z","2021-05-17T00:00:00.000Z","2021-05-18T00:00:00.000Z","2021-05-19T00:00:00.000Z","2021-05-20T00:00:00.000Z","2021-05-21T00:00:00.000Z","2021-05-24T00:00:00.000Z","2021-05-25T00:00:00.000Z","2021-05-26T00:00:00.000Z","2021-05-27T00:00:00.000Z","2021-05-28T00:00:00.000Z","2021-06-01T00:00:00.000Z","2021-06-02T00:00:00.000Z","2021-06-03T00:00:00.000Z","2021-06-04T00:00:00.000Z","2021-06-07T00:00:00.000Z","2021-06-08T00:00:00.000Z","2021-06-09T00:00:00.000Z","2021-06-10T00:00:00.000Z","2021-06-11T00:00:00.000Z","2021-06-14T00:00:00.000Z","2021-06-15T00:00:00.000Z","2021-06-16T00:00:00.000Z","2021-06-17T00:00:00.000Z","2021-06-18T00:00:00.000Z","2021-06-21T00:00:00.000Z","2021-06-22T00:00:00.000Z","2021-06-23T00:00:00.000Z","2021-06-24T00:00:00.000Z","2021-06-25T00:00:00.000Z","2021-06-28T00:00:00.000Z","2021-06-29T00:00:00.000Z","2021-06-30T00:00:00.000Z","2021-07-01T00:00:00.000Z","2021-07-02T00:00:00.000Z","2021-07-06T00:00:00.000Z","2021-07-07T00:00:00.000Z","2021-07-08T00:00:00.000Z","2021-07-09T00:00:00.000Z","2021-07-12T00:00:00.000Z","2021-07-13T00:00:00.000Z","2021-07-14T00:00:00.000Z","2021-07-15T00:00:00.000Z","2021-07-16T00:00:00.000Z","2021-07-19T00:00:00.000Z","2021-07-20T00:00:00.000Z","2021-07-21T00:00:00.000Z","2021-07-22T00:00:00.000Z","2021-07-23T00:00:00.000Z","2021-07-26T00:00:00.000Z","2021-07-27T00:00:00.000Z","2021-07-28T00:00:00.000Z","2021-07-29T00:00:00.000Z","2021-07-30T00:00:00.000Z","2021-08-02T00:00:00.000Z","2021-08-03T00:00:00.000Z","2021-08-04T00:00:00.000Z","2021-08-05T00:00:00.000Z","2021-08-06T00:00:00.000Z","2021-08-09T00:00:00.000Z","2021-08-10T00:00:00.000Z","2021-08-11T00:00:00.000Z","2021-08-12T00:00:00.000Z","2021-08-13T00:00:00.000Z","2021-08-16T00:00:00.000Z","2021-08-17T00:00:00.000Z","2021-08-18T00:00:00.000Z","2021-08-19T00:00:00.000Z","2021-08-20T00:00:00.000Z","2021-08-23T00:00:00.000Z","2021-08-24T00:00:00.000Z","2021-08-25T00:00:00.000Z","2021-08-26T00:00:00.000Z","2021-08-27T00:00:00.000Z","2021-08-30T00:00:00.000Z","2021-08-31T00:00:00.000Z","2021-09-01T00:00:00.000Z","2021-09-02T00:00:00.000Z","2021-09-03T00:00:00.000Z","2021-09-07T00:00:00.000Z","2021-09-08T00:00:00.000Z","2021-09-09T00:00:00.000Z","2021-09-10T00:00:00.000Z","2021-09-13T00:00:00.000Z","2021-09-14T00:00:00.000Z","2021-09-15T00:00:00.000Z","2021-09-16T00:00:00.000Z","2021-09-17T00:00:00.000Z","2021-09-20T00:00:00.000Z","2021-09-21T00:00:00.000Z","2021-09-22T00:00:00.000Z","2021-09-23T00:00:00.000Z","2021-09-24T00:00:00.000Z","2021-09-27T00:00:00.000Z","2021-09-28T00:00:00.000Z","2021-09-29T00:00:00.000Z","2021-09-30T00:00:00.000Z","2021-10-01T00:00:00.000Z","2021-10-04T00:00:00.000Z","2021-10-05T00:00:00.000Z","2021-10-06T00:00:00.000Z","2021-10-07T00:00:00.000Z","2021-10-08T00:00:00.000Z","2021-10-11T00:00:00.000Z","2021-10-12T00:00:00.000Z","2021-10-13T00:00:00.000Z","2021-10-14T00:00:00.000Z","2021-10-15T00:00:00.000Z","2021-10-18T00:00:00.000Z","2021-10-19T00:00:00.000Z","2021-10-20T00:00:00.000Z","2021-10-21T00:00:00.000Z","2021-10-22T00:00:00.000Z","2021-10-25T00:00:00.000Z","2021-10-26T00:00:00.000Z","2021-10-27T00:00:00.000Z","2021-10-28T00:00:00.000Z","2021-10-29T00:00:00.000Z","2021-11-01T00:00:00.000Z","2021-11-02T00:00:00.000Z","2021-11-03T00:00:00.000Z","2021-11-04T00:00:00.000Z","2021-11-05T00:00:00.000Z","2021-11-08T00:00:00.000Z","2021-11-09T00:00:00.000Z","2021-11-10T00:00:00.000Z","2021-11-11T00:00:00.000Z","2021-11-12T00:00:00.000Z","2021-11-15T00:00:00.000Z","2021-11-16T00:00:00.000Z","2021-11-17T00:00:00.000Z","2021-11-18T00:00:00.000Z","2021-11-19T00:00:00.000Z","2021-11-22T00:00:00.000Z","2021-11-23T00:00:00.000Z","2021-11-24T00:00:00.000Z","2021-11-26T00:00:00.000Z","2021-11-29T00:00:00.000Z","2021-11-30T00:00:00.000Z","2021-12-01T00:00:00.000Z","2021-12-02T00:00:00.000Z","2021-12-03T00:00:00.000Z","2021-12-06T00:00:00.000Z","2021-12-07T00:00:00.000Z","2021-12-08T00:00:00.000Z","2021-12-09T00:00:00.000Z","2021-12-10T00:00:00.000Z","2021-12-13T00:00:00.000Z","2021-12-14T00:00:00.000Z","2021-12-15T00:00:00.000Z","2021-12-16T00:00:00.000Z","2021-12-17T00:00:00.000Z","2021-12-20T00:00:00.000Z","2021-12-21T00:00:00.000Z","2021-12-22T00:00:00.000Z","2021-12-23T00:00:00.000Z","2021-12-27T00:00:00.000Z","2021-12-28T00:00:00.000Z","2021-12-29T00:00:00.000Z","2021-12-30T00:00:00.000Z","2021-12-31T00:00:00.000Z","2022-01-03T00:00:00.000Z","2022-01-04T00:00:00.000Z","2022-01-05T00:00:00.000Z","2022-01-06T00:00:00.000Z","2022-01-07T00:00:00.000Z","2022-01-10T00:00:00.000Z","2022-01-11T00:00:00.000Z","2022-01-12T00:00:00.000Z","2022-01-13T00:00:00.000Z","2022-01-14T00:00:00.000Z","2022-01-18T00:00:00.000Z","2022-01-19T00:00:00.000Z","2022-01-20T00:00:00.000Z","2022-01-21T00:00:00.000Z","2022-01-24T00:00:00.000Z","2022-01-25T00:00:00.000Z","2022-01-26T00:00:00.000Z","2022-01-27T00:00:00.000Z","2022-01-28T00:00:00.000Z"],[107.940002,105.580002,106.949997,109,108.18,110,109.199997,109.050003,109.660004,109.790001,110,112.370003,112.550003,112.769997,112.919998,114.019997,110.239998,111.290001,112.510002,111.43,110.75,107.93,106.440002,108.620003,108.800003,109.169998,109.019997,108.949997,109.669998,109.150002,108.900002,109.089996,110.099998,108.720001,108.489998,105.050003,107.720001,106.360001,104.349998,100.290001,101.919998,106.730003,108.290001,109.489998,106.449997,101.57,101.400002,101.610001,94.790001,98.739998,89.190002,91.599998,91.5,90.949997,92.239998,89.730003,100,93.529999,90.470001,96.529999,96.769997,97.790001,98.379997,98.099998,102.809998,105.389999,107.129997,106.949997,106,105.650002,111.800003,110.739998,114.75,116.709999,114.839996,114.68,114.360001,114.699997,115.669998,117.970001,116,111.870003,112.480003,113.129997,113.910004,118.32,115,116.269997,116.25,116.93,117.68,117.07,116.5,116.220001,116.709999,116.769997,119.099998,119.879997,117.220001,120.440002,115.07,117.989998,122.290001,123.279999,123.25,122.150002,117.480003,115.440002,116.5,120.099998,122.150002,124.660004,123.099998,122.900002,127.139999,126.730003,128.100006,131.130005,131.020004,131.320007,130.550003,131.479996,130.919998,130.979996,132.610001,132.039993,136.419998,135.470001,133.869995,135.910004,136.360001,139.419998,141.009995,134.199997,137.979996,137.839996,138.179993,139.429993,141.559998,140.949997,139.300003,133.75,135.490005,135.419998,135.770004,135.699997,142.039993,141.550003,143.240005,145.820007,146.330002,146.429993,142.770004,141.149994,136.880005,141.119995,141.639999,139.25,140.600006,142.279999,141.619995,142.759995,142.270004,142.009995,142.059998,143.380005,142.339996,141.080002,140.740005,138,138.240005,131.630005,127.459999,126.540001,129.880005,127.989998,127.93,127.989998,128.990005,124.220001,125.489998,124.330002,129.839996,131.570007,128.210007,129.509995,133.360001,132.059998,129.729996,132.070007,131.369995,130.089996,130.360001,126.410004,126.099998,126.860001,128.979996,131.869995,133.789993,131.070007,132.5,133.139999,130.419998,127.980003,127.779999,127.239998,126.410004,127.360001,125.620003,125.790001,122.989998,120.940002,120.75,124.879997,128.880005,119.5,116.459999,116.989998,120.300003,120.93,120.220001,119.25,119.330002,118.339996,116.739998,119.529999,122.029999,121.489998,120.809998,123.580002,124.769997,127.580002,127.029999,130.5,126.419998,129.190002,130.429993,131.559998,131.660004,134.779999,138.5,137.809998,139.5,141.949997,140.660004,141.630005,141.240005,139.520004,141.320007,142.330002,141,141.389999,141.910004,143.440002,140.229996,138.520004,137.330002,140.860001,141.520004,141.089996,138.570007,136.830002,139.259995,139.410004,142.429993,145.610001,144.979996,148.809998,146.360001,145.830002,146.199997,141,143.789993,146.149994,144.360001,140.559998,139.910004,142,142.570007,146.949997,145.330002,146.820007,146.850006,145.070007,146.050003,147.679993,144.660004,140.229996,138.300003,137.25,135.710007,134.839996,137.149994,135.929993,132.570007,131.529999,131.990005,130.240005,132.639999,132.460007,129.929993,130.440002,132.460007,131.25,130.039993,128.520004,129.410004,131.539993,132.970001,129.059998,130.240005,132.509995,133.410004,134.710007,136.729996,137.509995,141.089996,141.300003,142.839996,140.600006,139.419998,142.589996,141.919998,141.610001,142.110001,140,139.600006,140.309998,141.110001,142.520004,143.630005,144.360001,144.089996,144.300003,145.100006,142.710007,140.729996,138.020004,137.580002,142.589996,141.449997,138.899994,141.660004,138.919998,140.210007,137.050003,137.309998,135.979996,139.919998,142.470001,141.389999,142.589996,144,143.320007,143.309998,142.169998,143.690002,140.889999,142.899994,144.740005,146.449997,146.279999,146.360001,145.229996,146.660004,148.919998,143.960007,142.139999,142,139.380005,141.169998,140.919998,138.559998,139.190002,139.690002,143.179993,144.320007,143.460007,143.289993,143.539993,144.089996,141.320007,139.550003,142.550003,143.440002,143.309998,143.350006,142.630005,143.050003,141.350006,143.889999,140.070007,142.649994,145.119995,145.059998,142.350006,143.949997,142.839996,145,142.639999,139.520004,144.830002,136.470001,136.710007,136.110001,137.919998,138.110001,138.940002,137.960007,139.169998,140.940002,139.380005,140.919998,140.149994,143.160004,142.770004,141.979996,141.520004,142.199997,143.660004,145.339996,146.869995,144.960007,147.089996,145.759995,143.270004,142.020004,145.410004,145.220001,142.149994,137.910004,135.169998,131.979996,130.009995,126.190002,126.989998,127.040001,129.270004,131.860001,133.850006,139.309998,141.899994,143.360001,143.130005,143.580002,134.759995,137.479996,139.919998,139.529999,136.960007,136.720001,135.850006,134.649994,135.479996,137.460007,139.210007,141,141.110001,142.919998,142.679993,140.25,140.419998,140.910004,141.559998,137.699997,143.380005,144.190002,139.990005,139.350006,139.669998,140.149994,143.860001,143.610001,141.169998,138.619995,137.279999,137.259995,131.699997,125.75,128.25,130.800003,125.900002,125.879997,125.099998,120.650002,123.639999,127.440002,127.25,126.379997,126.489998,126.150002,125.639999,125.980003,127.699997,128.610001,129.339996,126.459999,130.970001,132.080002,131.279999,133.270004,133.240005,133.899994,133.699997,134.460007,131.929993,134.320007,136.300003,133.279999,129.089996,131.410004,127.57,131.240005,133.029999,130.039993,138.440002,135.520004,137.850006,138.279999,137.089996,133.570007,131.070007,130.770004,131.160004],[108.349998,107.75,109.309998,109.25,110,110.339996,109.269997,110.07,110.169998,110.449997,111.290001,112.989998,112.970001,114.040001,113.730003,114.129997,111.190002,112.879997,112.959999,111.889999,110.75,109.449997,107.419998,108.959999,110.349998,110.959999,109.760002,109.230003,109.980003,109.339996,109.889999,109.830002,110.900002,109.370003,108.940002,107.93,109.220001,108.260002,106.400002,101.889999,106.93,109.709999,111.940002,111.93,108.760002,104.18,103.57,102.169998,99.419998,99.610001,96.120003,98.199997,97.690002,93.980003,94.370003,97.720001,103.099998,94.150002,99.57,99.68,99.290001,101,99.839996,102.82,104.349998,107.5,107.459999,108.239998,109.379997,109.779999,113.019997,114.470001,118.690002,117,116.529999,116.199997,115.07,116.629997,116.68,118.470001,116.489998,114.449997,114.489998,114.360001,117.559998,120.190002,117.160004,116.940002,117.519997,118.5,119.519997,119.160004,117.260002,118.900002,117.919998,119.370003,121.760002,119.879997,120.010002,120.480003,117.760002,122.099998,123.139999,124.279999,123.529999,122.150002,119.110001,119.199997,119.580002,121.760002,125.660004,127.540001,124.760002,127.5,127.870003,129.009995,129.449997,131.240005,131.860001,133.600006,131.600006,131.889999,131.380005,132.369995,132.610001,135.520004,136.419998,136.520004,137.419998,136.339996,139.110001,141.25,141.580002,138.789993,138.979996,138.360001,138.729996,142.309998,141.990005,140.949997,139.570007,136.259995,137.139999,136.309998,136.509995,138.839996,142.839996,143.429993,146.5,146.339996,147.360001,146.839996,143.990005,141.149994,140.300003,142.850006,142.009995,140.970001,142.740005,143.619995,143.960007,142.990005,142.839996,142.399994,144.5,143.740005,142.339996,141.110001,140.740005,140.300003,138.240005,132.649994,127.5,129.520004,131.130005,128.389999,128.009995,129.860001,129.520004,126.540001,126.699997,128.470001,131.220001,132.320007,130.309998,132.009995,133.850006,132.429993,131.990005,134.059998,132.240005,132.949997,130.399994,126.5,126.379997,128.440002,132.070007,133.539993,133.860001,132.410004,133.259995,133.889999,130.600006,129.449997,128.009995,127.650002,127.5,127.580002,127.07,126.169998,124.089996,121.059998,121.459999,126.980003,128.880005,120.699997,121.300003,120.529999,120.639999,122.32,121.459999,120.709999,120.650002,118.580002,121.519997,123,123.389999,121.970001,123.559998,125,128.399994,128,129.75,130.869995,129.149994,130.979996,132.539993,133.630005,135.369995,137.110001,138.589996,140.800003,143.449997,142.5,142.970001,142.369995,141.720001,142.389999,142.199997,142.550003,142.130005,142.630005,143.860001,143.649994,141.399994,140.199997,140.869995,142,141.720001,141.800003,138.949997,139.380005,140.660004,143,145.919998,147.279999,146.479996,150.300003,146.960007,148.929993,146.630005,144.570007,147.289993,150.300003,144.610001,142.149994,142.470001,142.490005,148.229996,147.410004,147.940002,147.839996,147.910004,146.029999,148.410004,148.979996,145.399994,141.970001,139.619995,138.960007,137.830002,137.860001,138.279999,136.75,134.770004,132.929993,132.520004,133.039993,132.639999,132.809998,131,130.940002,133.699997,131.25,130.580002,129.809998,132.460007,134.479996,133.309998,130.429993,133,136.009995,134.509995,136.669998,138.419998,141.75,142.419998,142.770004,143.229996,140.729996,141.690002,143.880005,143.050003,142.970001,142.410004,141.350006,141.75,141.199997,143.270004,143.600006,145.389999,144.429993,144.949997,146.720001,146.289993,143.470001,140.880005,140.610001,141.419998,143.839996,143.330002,142.470001,142.699997,140.940002,140.710007,138.350006,140.690002,139.199997,143.100006,143.190002,142.669998,143.839996,145.729996,144.460007,144.210007,144.149994,143.860001,142.550003,145.820007,145.960007,147.259995,147.440002,146.399994,146.759995,148.740005,148.929993,144.259995,143.550003,142.639999,142.089996,141.660004,141.669998,139.5,139.720001,144.470001,144.529999,144.639999,143.820007,143.910004,143.789993,144.25,142.380005,141.479996,142.550003,145.919998,145,144.5,144.009995,145.169998,141.990005,143.889999,142.460007,145.360001,146.009995,145.220001,145.169998,144.630005,145.399994,145.639999,143.320007,141.339996,146.5,137.330002,137.839996,137.089996,138.449997,139.020004,139.399994,140.020004,142.160004,141.899994,141.410004,141.779999,143.5,144.350006,142.770004,142.889999,143.320007,144.330002,147.130005,147,147.759995,146.949997,147.089996,147.539993,144.240005,146.929993,146.910004,145.940002,142.240005,139.699997,135.559998,132.529999,130.5,127.620003,129.119995,130.020004,132.559998,135,139.589996,144.130005,144.110001,145.460007,144.729996,143.580002,138.119995,140.559998,140.610001,139.830002,137.759995,137.660004,136.690002,135.729996,136.770004,139.320007,140.839996,144.160004,143.789993,144.110001,142.759995,141.190002,140.839996,143.410004,141.75,140.720001,146.720001,144.699997,140.320007,141,141.960007,145.809998,146.589996,144.389999,143.360001,140.699997,137.820007,137.419998,131.830002,129.210007,128.570007,130.889999,126.110001,128.589996,125.959999,123.760002,125.599998,127.809998,128,127.330002,126.879997,127.370003,128.300003,128.339996,129.240005,129.779999,130.800003,130.130005,132.320007,133.25,133.009995,133.75,134.970001,134.169998,135.600006,134.990005,135.979996,136.300003,137.479996,133.970001,132.470001,132.169998,130.960007,132.910004,133.029999,130.75,142.550003,138.220001,141.990005,140.690002,139.399994,134.020004,132.330002,134.039993,132.229996],[106.760002,105.120003,106.629997,107.730003,107.779999,108.269997,108.199997,108.620003,108.709999,109.139999,109.949997,111.550003,111.769997,112.68,112,111.629997,109.949997,111.059998,111.239998,110.309998,105.5,104.400002,105.330002,107.120003,108.410004,108.739998,108.230003,107.940002,108.589996,107.970001,108.75,108.699997,109.400002,107.449997,106.800003,105.019997,105.239998,105.599998,102.720001,98.589996,101.709999,105.379997,108.059998,109.110001,105,99.910004,96.650002,98.330002,92.550003,92.75,85.690002,87.110001,85.919998,86,86.75,88.43,90.809998,89.459999,90.080002,94.629997,96.169998,96.620003,96.699997,97.5,100.790001,104.550003,100.110001,105.25,105.059998,104.650002,110,110.209999,114.529999,112.650002,113.919998,112.110001,111.18,113.690002,114.089996,115.129997,110.919998,110.860001,112.400002,112.059998,113.650002,116.300003,111.830002,114.730003,115.580002,116.349998,116.290001,114.519997,114.459999,116.110001,114.730003,116.720001,119.059998,117.199997,116.620003,116.190002,111.110001,116.769997,119.269997,122.370003,120.68,117.190002,116.050003,113.279999,115.889999,118.540001,121.459999,121.940002,119.809998,122.709999,125.059998,126.290001,128.100006,127.900002,128.800003,130.199997,128.649994,129.089996,128.089996,129.199997,130.699997,131.330002,133.470001,133.509995,133.800003,134.509995,136.059998,138.289993,134.770004,133.479996,135.839996,135.75,136.839996,138.75,138.889999,137.869995,134.729996,132.720001,134.820007,134.389999,134.690002,135.25,137.100006,139.550003,143.100006,143.259995,144.5,142.320007,139.5,135.559998,136.179993,140.580002,139.949997,138.309998,140.160004,141.070007,141.050003,140.839996,141.210007,141,142.059998,139.850006,140.009995,138.089996,137.080002,136.639999,131.220001,126.910004,123.330002,124.889999,126.339996,124.400002,125.93,127.5,126.470001,123.540001,123.370003,124.150002,128.460007,127.940002,128.089996,128.690002,130.869995,129.5,129.449997,131.460007,127.709999,129.070007,124.519997,123.970001,124.419998,125.919998,127.830002,130.160004,131.740005,129.880005,131.050003,129.509995,127.089996,127.300003,125.400002,125.529999,125.029999,126.099998,124.809998,122.769997,118.519997,117.790001,119.400002,123.720001,126.279999,114.529999,110.150002,114.779999,117.589996,118.970001,119.370003,117.550003,118.050003,116.650002,116.410004,119.099998,120.440002,119.739998,120.599998,122.410004,123.269997,125.660004,126.480003,128.179993,126.25,128.880005,129.720001,130.839996,131.25,134.630005,136.600006,137.110001,139.330002,138.320007,139.580002,138.970001,138.690002,138.630005,140.779999,138.779999,140.279999,140.889999,141.910004,138.160004,138.490005,136.389999,137,139.929993,139.309998,137.300003,134.630005,136.130005,137.910004,138,141.789993,144.740005,144.509995,145.380005,145.190002,144.539993,142.899994,140.470001,143.529999,146.149994,138.039993,137.759995,139.300003,139.339996,142.429993,144.119995,144.610001,145.039993,144.619995,143.369995,144.179993,145.440002,142,136.190002,136.929993,134.100006,133.910004,134.759995,135.600006,132.720001,130.509995,129.509995,127.169998,129.970001,129.809998,131,129.210007,129.139999,131.5,128.75,127.290001,127.980003,128.600006,131.039993,129.710007,128.169998,129.679993,131.529999,132.440002,134.270004,136.279999,137.270004,140.399994,140.759995,140.690002,138.440002,139.330002,141.449997,141.270004,140.619995,140.270004,138.75,138.830002,139.089996,140.419998,140.839996,143.039993,142.5,143.320007,143.490005,141.899994,141.050003,135.75,137.630005,137.580002,141.779999,140.619995,138.690002,137.789993,138.029999,137.850006,136.449997,136.759995,135.559998,139.009995,139.880005,140.169998,141.5,143.179993,142.520004,142.720001,142.169998,140.929993,140.649994,142.639999,144.050003,145.199997,145.570007,142.309998,144.979996,146.149994,144.309998,140.449997,140.669998,139.919998,138.789993,140.070007,138.229996,137.600006,138.050003,139.490005,142.229996,143.149994,141.429993,142.130005,141.960007,142.539993,140.039993,139.490005,140.559998,142.460007,142.529999,141.570007,141.229996,140.360001,139.880005,140.199997,140.070007,141.770004,143.800003,140.320007,142.240005,142.880005,142.449997,143.809998,137.169998,138.360001,134.839996,135.410004,135.429993,135.160004,137.059998,136.929993,138.190002,137.399994,138.639999,139.820007,139.080002,139.630005,139.320007,142.160004,140.009995,141.179993,141.210007,141.009995,142.600006,144.949997,144.990005,144.960007,145.119995,143.899994,140.809998,141.470001,143.910004,144.309998,135.839996,135.529999,133.199997,128.759995,126.559998,124.879997,126.120003,126.860001,128.940002,131.520004,133.809998,138.850006,139.539993,140.020004,142.600006,132.860001,134.399994,137.410004,137.509995,136,132.949997,134.619995,133.270004,134.199997,134.5,137.210007,138.270004,140.600006,140.5,141.720001,140.309998,139.100006,138.910004,140.020004,138.740005,136.419998,142,138.610001,137.639999,138.669998,138.5,139.75,143.539993,137.639999,138.570007,137.600006,135.110001,132.190002,125.309998,125.589996,124.809998,125.470001,123.07,123.279999,120.080002,120.650002,123.089996,124.879997,125.93,125.129997,124.690002,124.660004,125.639999,125.980003,125.82,128.020004,127.279999,126.459999,129.190002,130.550003,130.860001,132.300003,133.039993,131.889999,133.699997,131.649994,131.75,133.779999,133.630005,129.419998,127.279999,128.149994,127.550003,129.970001,130.509995,128.720001,133.449997,134.699997,137.850006,138.089996,131.899994,129.539993,128.830002,130.649994,129.580002],[107.339996,107.199997,108.779999,108.389999,109.489998,109.360001,108.589996,109.82,109.580002,109.610001,111.260002,112.93,112.410004,113.089996,113.480003,112.330002,110.559998,111.900002,112.209999,111.639999,107.919998,105.040001,107.07,107.82,110,109.089996,108.699997,109.040001,109.720001,108.839996,109.690002,109.459999,109.779999,109.199997,108.010002,107.029999,105.379997,106.540001,102.739998,101.370003,106.889999,106.699997,111.830002,110.209999,107.669998,100.93,103.379997,101.18,93.349998,97.059998,88.669998,95.410004,90.209999,90.059998,86.940002,95.470001,94.300003,89.639999,99.199997,95.370003,97.690002,100.169998,97.529999,102.290001,102.830002,106.510002,106.32,106.800003,105.800003,109.300003,112.029999,113.510002,118.099998,115.150002,115.410004,113.269997,114.57,114.459999,116.309998,116.019997,111.349998,112.779999,114.260002,113.269997,116.830002,119.610001,115.32,116.800003,116.620003,117.370003,116.370003,116.900002,117.120003,118.129997,117.120003,118.540001,119.550003,117.360001,119.82,116.639999,117.379997,121.349998,122.879997,122.779999,122.360001,117.93,117.18,118.32,119.510002,121.07,124.809998,122.419998,121.970001,126.519997,125.730003,128.110001,129.350006,130.190002,129.720001,130.600006,130.869995,130.740005,130.929993,130.690002,132.050003,135.220001,133.839996,134.270004,134.779999,135.610001,138.770004,140.809998,135.309998,138.529999,138.429993,138.050003,138.309998,141.529999,139.339996,138.300003,135.360001,135.240005,136.160004,134.779999,135.929993,138.589996,141.619995,142.360001,146.320007,146.179993,146.949997,143.990005,140.699997,135.699997,139.899994,141.770004,140.429993,140.449997,142.580002,141.860001,143.479996,141.210007,142.330002,142.210007,143.630005,141.770004,140.869995,139.470001,138.289993,139.559998,132.820007,130.130005,124.300003,128.699997,127.260002,126.019997,126.18,128.330002,126.739998,125.260002,125.900002,128.289993,131.020004,128.419998,129.320007,131.190002,132.279999,130.020004,130.410004,132.779999,129.070007,130.720001,124.839996,125.010002,125.989998,127.449997,130.880005,132.940002,132.75,131.339996,131.919998,129.869995,127.360001,127.650002,126.919998,126.769997,126.68,126.620003,125.599998,123.900002,119.830002,119.809998,120.739998,125.309998,128.330002,119.190002,116.970001,118.93,119.779999,119.32,120.800003,118.599998,118.519997,116.839996,120.139999,121.870003,121.860001,120.25,121.510002,124.169998,127.75,127.239998,129.539993,128.380005,128.690002,130.839996,132.149994,133.169998,134.679993,135.800003,137.539993,140.660004,141.600006,139.850006,142.610001,141.009995,139.429993,141.509995,141.809998,140.720001,140.699997,142.050003,143.600006,139.509995,141.320007,136.800003,140.740005,141.860001,141.220001,139.059998,136.339996,138.940002,139,141.429993,145.600006,145.970001,146,146.300003,146.300003,146.229996,143.009995,143.199997,145.869995,148.970001,140.820007,138.630005,141.220001,142.460007,146.110001,144.610001,147.330002,147.740005,145.779999,145.830002,147.410004,145.949997,142.259995,141.169998,137.679993,135.240005,133.970001,137.270004,136.820007,133.050003,131.289993,132.600006,127.209999,130.929993,130.119995,131.339996,130.490005,130.889999,131.740005,130.600006,128,128.399994,131.410004,133.050003,129.800003,130.029999,132.850006,134.970001,134.429993,135.369995,137.960007,141.539993,141.279999,142.009995,141.550003,140.460007,141.449997,142.110001,141.610001,142.770004,141.050003,139.630005,140.860001,141.039993,141.259995,143.139999,143.789993,143.460007,143.990005,146.339996,142.080002,141.179993,137.059998,137.860001,141.339996,142.419998,140.649994,141.360001,139.669998,139.130005,138.619995,137.529999,138.059998,138.880005,141.809998,140.169998,142.089996,143.259995,143.990005,142.929993,142.929993,143.619995,141.399994,141.990005,145.210007,145.720001,145.5,145.820007,145.660004,146.389999,148.550003,144.800003,142.600006,141.929993,141.119995,140.960007,140.860001,138.619995,138.649994,138.589996,142.979996,144.100006,143.830002,142.139999,143.410004,143,142.949997,140.449997,140.990005,141.389999,143.25,143.119995,142.660004,143.100006,141.240005,141.070007,140.720001,142.289993,144.990005,145.25,141.929993,143.559998,143.380005,143.960007,144.110001,139.800003,139.910004,136.869995,136.339996,136.160004,137.029999,138.300003,138.990005,138.679993,140,141.039993,139.990005,140.600006,140.169998,142.820007,142.570007,141.860001,141.470001,142.940002,143.289993,145.210007,146.429993,145.399994,146.600006,145.220001,144.100006,142.309998,145.130005,144.679993,145.369995,137.039993,135.960007,133.880005,130.089996,126.760002,126.400002,127.889999,129.899994,131.979996,133.770004,137.940002,142.25,143.589996,143.160004,144.089996,134.070007,137.589996,139.990005,139.470001,136.669998,136.440002,135.710007,134.75,134.710007,136.75,139.199997,140.630005,141.070007,142.190002,142.399994,140.369995,140.229996,140.25,141.770004,140.169998,139.5,142.479996,139.570007,138.160004,139.789993,139.279999,144.449997,145.440002,141.279999,139.559998,138.139999,137.330002,132.389999,126.279999,128.410004,126.650002,125.970001,124.879997,124.220001,120.230003,122.589996,125.269997,126.309998,126.150002,126.370003,125,125.639999,126.769997,126.849998,128.899994,129.389999,127.519997,129.919998,132.169998,131.470001,132.539993,133.039993,133.470001,133.139999,134.460007,131.899994,134.949997,135.759995,133.800003,129.690002,131.779999,128.899994,130.800003,132.5,130.839996,130.440002,133.910004,136.910004,138.880005,139.009995,135.199997,131.009995,129.979996,131.059998,131.919998]]},"evals":[],"jsHooks":[]}</script>
<p><br /></p>
<ul>
<li>subset for individual columns.</li>
<li>easily add annotations for events.</li>
</ul>
<pre class="r"><code>## use dyEvent to add annotations
graph &lt;- dygraph(price$EA.Close)
graph &lt;- dyEvent(graph, &quot;2020-02-21&quot;,&quot;Start of Covid 19&quot;, labelLoc = &#39;top&#39;)
graph &lt;- dyEvent(graph, &quot;2021-06-10&quot;,&quot;New product announcements&quot;, labelLoc = &#39;top&#39;)
## print chart
graph</code></pre>
<div id="htmlwidget-2" style="width:768px;height:384px;" class="dygraphs html-widget"></div>
<script type="application/json" data-for="htmlwidget-2">{"x":{"attrs":{"labels":["day","EA.Close"],"legend":"auto","retainDateWindow":false,"axes":{"x":{"pixelsPerLabel":60}}},"scale":"daily","annotations":[],"shadings":[],"events":[{"pos":"2020-02-21T00:00:00.000Z","label":"Start of Covid 19","labelLoc":"top","color":"black","strokePattern":[7,3],"axis":"x"},{"pos":"2021-06-10T00:00:00.000Z","label":"New product announcements","labelLoc":"top","color":"black","strokePattern":[7,3],"axis":"x"}],"format":"date","data":[["2020-01-02T00:00:00.000Z","2020-01-03T00:00:00.000Z","2020-01-06T00:00:00.000Z","2020-01-07T00:00:00.000Z","2020-01-08T00:00:00.000Z","2020-01-09T00:00:00.000Z","2020-01-10T00:00:00.000Z","2020-01-13T00:00:00.000Z","2020-01-14T00:00:00.000Z","2020-01-15T00:00:00.000Z","2020-01-16T00:00:00.000Z","2020-01-17T00:00:00.000Z","2020-01-21T00:00:00.000Z","2020-01-22T00:00:00.000Z","2020-01-23T00:00:00.000Z","2020-01-24T00:00:00.000Z","2020-01-27T00:00:00.000Z","2020-01-28T00:00:00.000Z","2020-01-29T00:00:00.000Z","2020-01-30T00:00:00.000Z","2020-01-31T00:00:00.000Z","2020-02-03T00:00:00.000Z","2020-02-04T00:00:00.000Z","2020-02-05T00:00:00.000Z","2020-02-06T00:00:00.000Z","2020-02-07T00:00:00.000Z","2020-02-10T00:00:00.000Z","2020-02-11T00:00:00.000Z","2020-02-12T00:00:00.000Z","2020-02-13T00:00:00.000Z","2020-02-14T00:00:00.000Z","2020-02-18T00:00:00.000Z","2020-02-19T00:00:00.000Z","2020-02-20T00:00:00.000Z","2020-02-21T00:00:00.000Z","2020-02-24T00:00:00.000Z","2020-02-25T00:00:00.000Z","2020-02-26T00:00:00.000Z","2020-02-27T00:00:00.000Z","2020-02-28T00:00:00.000Z","2020-03-02T00:00:00.000Z","2020-03-03T00:00:00.000Z","2020-03-04T00:00:00.000Z","2020-03-05T00:00:00.000Z","2020-03-06T00:00:00.000Z","2020-03-09T00:00:00.000Z","2020-03-10T00:00:00.000Z","2020-03-11T00:00:00.000Z","2020-03-12T00:00:00.000Z","2020-03-13T00:00:00.000Z","2020-03-16T00:00:00.000Z","2020-03-17T00:00:00.000Z","2020-03-18T00:00:00.000Z","2020-03-19T00:00:00.000Z","2020-03-20T00:00:00.000Z","2020-03-23T00:00:00.000Z","2020-03-24T00:00:00.000Z","2020-03-25T00:00:00.000Z","2020-03-26T00:00:00.000Z","2020-03-27T00:00:00.000Z","2020-03-30T00:00:00.000Z","2020-03-31T00:00:00.000Z","2020-04-01T00:00:00.000Z","2020-04-02T00:00:00.000Z","2020-04-03T00:00:00.000Z","2020-04-06T00:00:00.000Z","2020-04-07T00:00:00.000Z","2020-04-08T00:00:00.000Z","2020-04-09T00:00:00.000Z","2020-04-13T00:00:00.000Z","2020-04-14T00:00:00.000Z","2020-04-15T00:00:00.000Z","2020-04-16T00:00:00.000Z","2020-04-17T00:00:00.000Z","2020-04-20T00:00:00.000Z","2020-04-21T00:00:00.000Z","2020-04-22T00:00:00.000Z","2020-04-23T00:00:00.000Z","2020-04-24T00:00:00.000Z","2020-04-27T00:00:00.000Z","2020-04-28T00:00:00.000Z","2020-04-29T00:00:00.000Z","2020-04-30T00:00:00.000Z","2020-05-01T00:00:00.000Z","2020-05-04T00:00:00.000Z","2020-05-05T00:00:00.000Z","2020-05-06T00:00:00.000Z","2020-05-07T00:00:00.000Z","2020-05-08T00:00:00.000Z","2020-05-11T00:00:00.000Z","2020-05-12T00:00:00.000Z","2020-05-13T00:00:00.000Z","2020-05-14T00:00:00.000Z","2020-05-15T00:00:00.000Z","2020-05-18T00:00:00.000Z","2020-05-19T00:00:00.000Z","2020-05-20T00:00:00.000Z","2020-05-21T00:00:00.000Z","2020-05-22T00:00:00.000Z","2020-05-26T00:00:00.000Z","2020-05-27T00:00:00.000Z","2020-05-28T00:00:00.000Z","2020-05-29T00:00:00.000Z","2020-06-01T00:00:00.000Z","2020-06-02T00:00:00.000Z","2020-06-03T00:00:00.000Z","2020-06-04T00:00:00.000Z","2020-06-05T00:00:00.000Z","2020-06-08T00:00:00.000Z","2020-06-09T00:00:00.000Z","2020-06-10T00:00:00.000Z","2020-06-11T00:00:00.000Z","2020-06-12T00:00:00.000Z","2020-06-15T00:00:00.000Z","2020-06-16T00:00:00.000Z","2020-06-17T00:00:00.000Z","2020-06-18T00:00:00.000Z","2020-06-19T00:00:00.000Z","2020-06-22T00:00:00.000Z","2020-06-23T00:00:00.000Z","2020-06-24T00:00:00.000Z","2020-06-25T00:00:00.000Z","2020-06-26T00:00:00.000Z","2020-06-29T00:00:00.000Z","2020-06-30T00:00:00.000Z","2020-07-01T00:00:00.000Z","2020-07-02T00:00:00.000Z","2020-07-06T00:00:00.000Z","2020-07-07T00:00:00.000Z","2020-07-08T00:00:00.000Z","2020-07-09T00:00:00.000Z","2020-07-10T00:00:00.000Z","2020-07-13T00:00:00.000Z","2020-07-14T00:00:00.000Z","2020-07-15T00:00:00.000Z","2020-07-16T00:00:00.000Z","2020-07-17T00:00:00.000Z","2020-07-20T00:00:00.000Z","2020-07-21T00:00:00.000Z","2020-07-22T00:00:00.000Z","2020-07-23T00:00:00.000Z","2020-07-24T00:00:00.000Z","2020-07-27T00:00:00.000Z","2020-07-28T00:00:00.000Z","2020-07-29T00:00:00.000Z","2020-07-30T00:00:00.000Z","2020-07-31T00:00:00.000Z","2020-08-03T00:00:00.000Z","2020-08-04T00:00:00.000Z","2020-08-05T00:00:00.000Z","2020-08-06T00:00:00.000Z","2020-08-07T00:00:00.000Z","2020-08-10T00:00:00.000Z","2020-08-11T00:00:00.000Z","2020-08-12T00:00:00.000Z","2020-08-13T00:00:00.000Z","2020-08-14T00:00:00.000Z","2020-08-17T00:00:00.000Z","2020-08-18T00:00:00.000Z","2020-08-19T00:00:00.000Z","2020-08-20T00:00:00.000Z","2020-08-21T00:00:00.000Z","2020-08-24T00:00:00.000Z","2020-08-25T00:00:00.000Z","2020-08-26T00:00:00.000Z","2020-08-27T00:00:00.000Z","2020-08-28T00:00:00.000Z","2020-08-31T00:00:00.000Z","2020-09-01T00:00:00.000Z","2020-09-02T00:00:00.000Z","2020-09-03T00:00:00.000Z","2020-09-04T00:00:00.000Z","2020-09-08T00:00:00.000Z","2020-09-09T00:00:00.000Z","2020-09-10T00:00:00.000Z","2020-09-11T00:00:00.000Z","2020-09-14T00:00:00.000Z","2020-09-15T00:00:00.000Z","2020-09-16T00:00:00.000Z","2020-09-17T00:00:00.000Z","2020-09-18T00:00:00.000Z","2020-09-21T00:00:00.000Z","2020-09-22T00:00:00.000Z","2020-09-23T00:00:00.000Z","2020-09-24T00:00:00.000Z","2020-09-25T00:00:00.000Z","2020-09-28T00:00:00.000Z","2020-09-29T00:00:00.000Z","2020-09-30T00:00:00.000Z","2020-10-01T00:00:00.000Z","2020-10-02T00:00:00.000Z","2020-10-05T00:00:00.000Z","2020-10-06T00:00:00.000Z","2020-10-07T00:00:00.000Z","2020-10-08T00:00:00.000Z","2020-10-09T00:00:00.000Z","2020-10-12T00:00:00.000Z","2020-10-13T00:00:00.000Z","2020-10-14T00:00:00.000Z","2020-10-15T00:00:00.000Z","2020-10-16T00:00:00.000Z","2020-10-19T00:00:00.000Z","2020-10-20T00:00:00.000Z","2020-10-21T00:00:00.000Z","2020-10-22T00:00:00.000Z","2020-10-23T00:00:00.000Z","2020-10-26T00:00:00.000Z","2020-10-27T00:00:00.000Z","2020-10-28T00:00:00.000Z","2020-10-29T00:00:00.000Z","2020-10-30T00:00:00.000Z","2020-11-02T00:00:00.000Z","2020-11-03T00:00:00.000Z","2020-11-04T00:00:00.000Z","2020-11-05T00:00:00.000Z","2020-11-06T00:00:00.000Z","2020-11-09T00:00:00.000Z","2020-11-10T00:00:00.000Z","2020-11-11T00:00:00.000Z","2020-11-12T00:00:00.000Z","2020-11-13T00:00:00.000Z","2020-11-16T00:00:00.000Z","2020-11-17T00:00:00.000Z","2020-11-18T00:00:00.000Z","2020-11-19T00:00:00.000Z","2020-11-20T00:00:00.000Z","2020-11-23T00:00:00.000Z","2020-11-24T00:00:00.000Z","2020-11-25T00:00:00.000Z","2020-11-27T00:00:00.000Z","2020-11-30T00:00:00.000Z","2020-12-01T00:00:00.000Z","2020-12-02T00:00:00.000Z","2020-12-03T00:00:00.000Z","2020-12-04T00:00:00.000Z","2020-12-07T00:00:00.000Z","2020-12-08T00:00:00.000Z","2020-12-09T00:00:00.000Z","2020-12-10T00:00:00.000Z","2020-12-11T00:00:00.000Z","2020-12-14T00:00:00.000Z","2020-12-15T00:00:00.000Z","2020-12-16T00:00:00.000Z","2020-12-17T00:00:00.000Z","2020-12-18T00:00:00.000Z","2020-12-21T00:00:00.000Z","2020-12-22T00:00:00.000Z","2020-12-23T00:00:00.000Z","2020-12-24T00:00:00.000Z","2020-12-28T00:00:00.000Z","2020-12-29T00:00:00.000Z","2020-12-30T00:00:00.000Z","2020-12-31T00:00:00.000Z","2021-01-04T00:00:00.000Z","2021-01-05T00:00:00.000Z","2021-01-06T00:00:00.000Z","2021-01-07T00:00:00.000Z","2021-01-08T00:00:00.000Z","2021-01-11T00:00:00.000Z","2021-01-12T00:00:00.000Z","2021-01-13T00:00:00.000Z","2021-01-14T00:00:00.000Z","2021-01-15T00:00:00.000Z","2021-01-19T00:00:00.000Z","2021-01-20T00:00:00.000Z","2021-01-21T00:00:00.000Z","2021-01-22T00:00:00.000Z","2021-01-25T00:00:00.000Z","2021-01-26T00:00:00.000Z","2021-01-27T00:00:00.000Z","2021-01-28T00:00:00.000Z","2021-01-29T00:00:00.000Z","2021-02-01T00:00:00.000Z","2021-02-02T00:00:00.000Z","2021-02-03T00:00:00.000Z","2021-02-04T00:00:00.000Z","2021-02-05T00:00:00.000Z","2021-02-08T00:00:00.000Z","2021-02-09T00:00:00.000Z","2021-02-10T00:00:00.000Z","2021-02-11T00:00:00.000Z","2021-02-12T00:00:00.000Z","2021-02-16T00:00:00.000Z","2021-02-17T00:00:00.000Z","2021-02-18T00:00:00.000Z","2021-02-19T00:00:00.000Z","2021-02-22T00:00:00.000Z","2021-02-23T00:00:00.000Z","2021-02-24T00:00:00.000Z","2021-02-25T00:00:00.000Z","2021-02-26T00:00:00.000Z","2021-03-01T00:00:00.000Z","2021-03-02T00:00:00.000Z","2021-03-03T00:00:00.000Z","2021-03-04T00:00:00.000Z","2021-03-05T00:00:00.000Z","2021-03-08T00:00:00.000Z","2021-03-09T00:00:00.000Z","2021-03-10T00:00:00.000Z","2021-03-11T00:00:00.000Z","2021-03-12T00:00:00.000Z","2021-03-15T00:00:00.000Z","2021-03-16T00:00:00.000Z","2021-03-17T00:00:00.000Z","2021-03-18T00:00:00.000Z","2021-03-19T00:00:00.000Z","2021-03-22T00:00:00.000Z","2021-03-23T00:00:00.000Z","2021-03-24T00:00:00.000Z","2021-03-25T00:00:00.000Z","2021-03-26T00:00:00.000Z","2021-03-29T00:00:00.000Z","2021-03-30T00:00:00.000Z","2021-03-31T00:00:00.000Z","2021-04-01T00:00:00.000Z","2021-04-05T00:00:00.000Z","2021-04-06T00:00:00.000Z","2021-04-07T00:00:00.000Z","2021-04-08T00:00:00.000Z","2021-04-09T00:00:00.000Z","2021-04-12T00:00:00.000Z","2021-04-13T00:00:00.000Z","2021-04-14T00:00:00.000Z","2021-04-15T00:00:00.000Z","2021-04-16T00:00:00.000Z","2021-04-19T00:00:00.000Z","2021-04-20T00:00:00.000Z","2021-04-21T00:00:00.000Z","2021-04-22T00:00:00.000Z","2021-04-23T00:00:00.000Z","2021-04-26T00:00:00.000Z","2021-04-27T00:00:00.000Z","2021-04-28T00:00:00.000Z","2021-04-29T00:00:00.000Z","2021-04-30T00:00:00.000Z","2021-05-03T00:00:00.000Z","2021-05-04T00:00:00.000Z","2021-05-05T00:00:00.000Z","2021-05-06T00:00:00.000Z","2021-05-07T00:00:00.000Z","2021-05-10T00:00:00.000Z","2021-05-11T00:00:00.000Z","2021-05-12T00:00:00.000Z","2021-05-13T00:00:00.000Z","2021-05-14T00:00:00.000Z","2021-05-17T00:00:00.000Z","2021-05-18T00:00:00.000Z","2021-05-19T00:00:00.000Z","2021-05-20T00:00:00.000Z","2021-05-21T00:00:00.000Z","2021-05-24T00:00:00.000Z","2021-05-25T00:00:00.000Z","2021-05-26T00:00:00.000Z","2021-05-27T00:00:00.000Z","2021-05-28T00:00:00.000Z","2021-06-01T00:00:00.000Z","2021-06-02T00:00:00.000Z","2021-06-03T00:00:00.000Z","2021-06-04T00:00:00.000Z","2021-06-07T00:00:00.000Z","2021-06-08T00:00:00.000Z","2021-06-09T00:00:00.000Z","2021-06-10T00:00:00.000Z","2021-06-11T00:00:00.000Z","2021-06-14T00:00:00.000Z","2021-06-15T00:00:00.000Z","2021-06-16T00:00:00.000Z","2021-06-17T00:00:00.000Z","2021-06-18T00:00:00.000Z","2021-06-21T00:00:00.000Z","2021-06-22T00:00:00.000Z","2021-06-23T00:00:00.000Z","2021-06-24T00:00:00.000Z","2021-06-25T00:00:00.000Z","2021-06-28T00:00:00.000Z","2021-06-29T00:00:00.000Z","2021-06-30T00:00:00.000Z","2021-07-01T00:00:00.000Z","2021-07-02T00:00:00.000Z","2021-07-06T00:00:00.000Z","2021-07-07T00:00:00.000Z","2021-07-08T00:00:00.000Z","2021-07-09T00:00:00.000Z","2021-07-12T00:00:00.000Z","2021-07-13T00:00:00.000Z","2021-07-14T00:00:00.000Z","2021-07-15T00:00:00.000Z","2021-07-16T00:00:00.000Z","2021-07-19T00:00:00.000Z","2021-07-20T00:00:00.000Z","2021-07-21T00:00:00.000Z","2021-07-22T00:00:00.000Z","2021-07-23T00:00:00.000Z","2021-07-26T00:00:00.000Z","2021-07-27T00:00:00.000Z","2021-07-28T00:00:00.000Z","2021-07-29T00:00:00.000Z","2021-07-30T00:00:00.000Z","2021-08-02T00:00:00.000Z","2021-08-03T00:00:00.000Z","2021-08-04T00:00:00.000Z","2021-08-05T00:00:00.000Z","2021-08-06T00:00:00.000Z","2021-08-09T00:00:00.000Z","2021-08-10T00:00:00.000Z","2021-08-11T00:00:00.000Z","2021-08-12T00:00:00.000Z","2021-08-13T00:00:00.000Z","2021-08-16T00:00:00.000Z","2021-08-17T00:00:00.000Z","2021-08-18T00:00:00.000Z","2021-08-19T00:00:00.000Z","2021-08-20T00:00:00.000Z","2021-08-23T00:00:00.000Z","2021-08-24T00:00:00.000Z","2021-08-25T00:00:00.000Z","2021-08-26T00:00:00.000Z","2021-08-27T00:00:00.000Z","2021-08-30T00:00:00.000Z","2021-08-31T00:00:00.000Z","2021-09-01T00:00:00.000Z","2021-09-02T00:00:00.000Z","2021-09-03T00:00:00.000Z","2021-09-07T00:00:00.000Z","2021-09-08T00:00:00.000Z","2021-09-09T00:00:00.000Z","2021-09-10T00:00:00.000Z","2021-09-13T00:00:00.000Z","2021-09-14T00:00:00.000Z","2021-09-15T00:00:00.000Z","2021-09-16T00:00:00.000Z","2021-09-17T00:00:00.000Z","2021-09-20T00:00:00.000Z","2021-09-21T00:00:00.000Z","2021-09-22T00:00:00.000Z","2021-09-23T00:00:00.000Z","2021-09-24T00:00:00.000Z","2021-09-27T00:00:00.000Z","2021-09-28T00:00:00.000Z","2021-09-29T00:00:00.000Z","2021-09-30T00:00:00.000Z","2021-10-01T00:00:00.000Z","2021-10-04T00:00:00.000Z","2021-10-05T00:00:00.000Z","2021-10-06T00:00:00.000Z","2021-10-07T00:00:00.000Z","2021-10-08T00:00:00.000Z","2021-10-11T00:00:00.000Z","2021-10-12T00:00:00.000Z","2021-10-13T00:00:00.000Z","2021-10-14T00:00:00.000Z","2021-10-15T00:00:00.000Z","2021-10-18T00:00:00.000Z","2021-10-19T00:00:00.000Z","2021-10-20T00:00:00.000Z","2021-10-21T00:00:00.000Z","2021-10-22T00:00:00.000Z","2021-10-25T00:00:00.000Z","2021-10-26T00:00:00.000Z","2021-10-27T00:00:00.000Z","2021-10-28T00:00:00.000Z","2021-10-29T00:00:00.000Z","2021-11-01T00:00:00.000Z","2021-11-02T00:00:00.000Z","2021-11-03T00:00:00.000Z","2021-11-04T00:00:00.000Z","2021-11-05T00:00:00.000Z","2021-11-08T00:00:00.000Z","2021-11-09T00:00:00.000Z","2021-11-10T00:00:00.000Z","2021-11-11T00:00:00.000Z","2021-11-12T00:00:00.000Z","2021-11-15T00:00:00.000Z","2021-11-16T00:00:00.000Z","2021-11-17T00:00:00.000Z","2021-11-18T00:00:00.000Z","2021-11-19T00:00:00.000Z","2021-11-22T00:00:00.000Z","2021-11-23T00:00:00.000Z","2021-11-24T00:00:00.000Z","2021-11-26T00:00:00.000Z","2021-11-29T00:00:00.000Z","2021-11-30T00:00:00.000Z","2021-12-01T00:00:00.000Z","2021-12-02T00:00:00.000Z","2021-12-03T00:00:00.000Z","2021-12-06T00:00:00.000Z","2021-12-07T00:00:00.000Z","2021-12-08T00:00:00.000Z","2021-12-09T00:00:00.000Z","2021-12-10T00:00:00.000Z","2021-12-13T00:00:00.000Z","2021-12-14T00:00:00.000Z","2021-12-15T00:00:00.000Z","2021-12-16T00:00:00.000Z","2021-12-17T00:00:00.000Z","2021-12-20T00:00:00.000Z","2021-12-21T00:00:00.000Z","2021-12-22T00:00:00.000Z","2021-12-23T00:00:00.000Z","2021-12-27T00:00:00.000Z","2021-12-28T00:00:00.000Z","2021-12-29T00:00:00.000Z","2021-12-30T00:00:00.000Z","2021-12-31T00:00:00.000Z","2022-01-03T00:00:00.000Z","2022-01-04T00:00:00.000Z","2022-01-05T00:00:00.000Z","2022-01-06T00:00:00.000Z","2022-01-07T00:00:00.000Z","2022-01-10T00:00:00.000Z","2022-01-11T00:00:00.000Z","2022-01-12T00:00:00.000Z","2022-01-13T00:00:00.000Z","2022-01-14T00:00:00.000Z","2022-01-18T00:00:00.000Z","2022-01-19T00:00:00.000Z","2022-01-20T00:00:00.000Z","2022-01-21T00:00:00.000Z","2022-01-24T00:00:00.000Z","2022-01-25T00:00:00.000Z","2022-01-26T00:00:00.000Z","2022-01-27T00:00:00.000Z","2022-01-28T00:00:00.000Z"],[107.339996,107.199997,108.779999,108.389999,109.489998,109.360001,108.589996,109.82,109.580002,109.610001,111.260002,112.93,112.410004,113.089996,113.480003,112.330002,110.559998,111.900002,112.209999,111.639999,107.919998,105.040001,107.07,107.82,110,109.089996,108.699997,109.040001,109.720001,108.839996,109.690002,109.459999,109.779999,109.199997,108.010002,107.029999,105.379997,106.540001,102.739998,101.370003,106.889999,106.699997,111.830002,110.209999,107.669998,100.93,103.379997,101.18,93.349998,97.059998,88.669998,95.410004,90.209999,90.059998,86.940002,95.470001,94.300003,89.639999,99.199997,95.370003,97.690002,100.169998,97.529999,102.290001,102.830002,106.510002,106.32,106.800003,105.800003,109.300003,112.029999,113.510002,118.099998,115.150002,115.410004,113.269997,114.57,114.459999,116.309998,116.019997,111.349998,112.779999,114.260002,113.269997,116.830002,119.610001,115.32,116.800003,116.620003,117.370003,116.370003,116.900002,117.120003,118.129997,117.120003,118.540001,119.550003,117.360001,119.82,116.639999,117.379997,121.349998,122.879997,122.779999,122.360001,117.93,117.18,118.32,119.510002,121.07,124.809998,122.419998,121.970001,126.519997,125.730003,128.110001,129.350006,130.190002,129.720001,130.600006,130.869995,130.740005,130.929993,130.690002,132.050003,135.220001,133.839996,134.270004,134.779999,135.610001,138.770004,140.809998,135.309998,138.529999,138.429993,138.050003,138.309998,141.529999,139.339996,138.300003,135.360001,135.240005,136.160004,134.779999,135.929993,138.589996,141.619995,142.360001,146.320007,146.179993,146.949997,143.990005,140.699997,135.699997,139.899994,141.770004,140.429993,140.449997,142.580002,141.860001,143.479996,141.210007,142.330002,142.210007,143.630005,141.770004,140.869995,139.470001,138.289993,139.559998,132.820007,130.130005,124.300003,128.699997,127.260002,126.019997,126.18,128.330002,126.739998,125.260002,125.900002,128.289993,131.020004,128.419998,129.320007,131.190002,132.279999,130.020004,130.410004,132.779999,129.070007,130.720001,124.839996,125.010002,125.989998,127.449997,130.880005,132.940002,132.75,131.339996,131.919998,129.869995,127.360001,127.650002,126.919998,126.769997,126.68,126.620003,125.599998,123.900002,119.830002,119.809998,120.739998,125.309998,128.330002,119.190002,116.970001,118.93,119.779999,119.32,120.800003,118.599998,118.519997,116.839996,120.139999,121.870003,121.860001,120.25,121.510002,124.169998,127.75,127.239998,129.539993,128.380005,128.690002,130.839996,132.149994,133.169998,134.679993,135.800003,137.539993,140.660004,141.600006,139.850006,142.610001,141.009995,139.429993,141.509995,141.809998,140.720001,140.699997,142.050003,143.600006,139.509995,141.320007,136.800003,140.740005,141.860001,141.220001,139.059998,136.339996,138.940002,139,141.429993,145.600006,145.970001,146,146.300003,146.300003,146.229996,143.009995,143.199997,145.869995,148.970001,140.820007,138.630005,141.220001,142.460007,146.110001,144.610001,147.330002,147.740005,145.779999,145.830002,147.410004,145.949997,142.259995,141.169998,137.679993,135.240005,133.970001,137.270004,136.820007,133.050003,131.289993,132.600006,127.209999,130.929993,130.119995,131.339996,130.490005,130.889999,131.740005,130.600006,128,128.399994,131.410004,133.050003,129.800003,130.029999,132.850006,134.970001,134.429993,135.369995,137.960007,141.539993,141.279999,142.009995,141.550003,140.460007,141.449997,142.110001,141.610001,142.770004,141.050003,139.630005,140.860001,141.039993,141.259995,143.139999,143.789993,143.460007,143.990005,146.339996,142.080002,141.179993,137.059998,137.860001,141.339996,142.419998,140.649994,141.360001,139.669998,139.130005,138.619995,137.529999,138.059998,138.880005,141.809998,140.169998,142.089996,143.259995,143.990005,142.929993,142.929993,143.619995,141.399994,141.990005,145.210007,145.720001,145.5,145.820007,145.660004,146.389999,148.550003,144.800003,142.600006,141.929993,141.119995,140.960007,140.860001,138.619995,138.649994,138.589996,142.979996,144.100006,143.830002,142.139999,143.410004,143,142.949997,140.449997,140.990005,141.389999,143.25,143.119995,142.660004,143.100006,141.240005,141.070007,140.720001,142.289993,144.990005,145.25,141.929993,143.559998,143.380005,143.960007,144.110001,139.800003,139.910004,136.869995,136.339996,136.160004,137.029999,138.300003,138.990005,138.679993,140,141.039993,139.990005,140.600006,140.169998,142.820007,142.570007,141.860001,141.470001,142.940002,143.289993,145.210007,146.429993,145.399994,146.600006,145.220001,144.100006,142.309998,145.130005,144.679993,145.369995,137.039993,135.960007,133.880005,130.089996,126.760002,126.400002,127.889999,129.899994,131.979996,133.770004,137.940002,142.25,143.589996,143.160004,144.089996,134.070007,137.589996,139.990005,139.470001,136.669998,136.440002,135.710007,134.75,134.710007,136.75,139.199997,140.630005,141.070007,142.190002,142.399994,140.369995,140.229996,140.25,141.770004,140.169998,139.5,142.479996,139.570007,138.160004,139.789993,139.279999,144.449997,145.440002,141.279999,139.559998,138.139999,137.330002,132.389999,126.279999,128.410004,126.650002,125.970001,124.879997,124.220001,120.230003,122.589996,125.269997,126.309998,126.150002,126.370003,125,125.639999,126.769997,126.849998,128.899994,129.389999,127.519997,129.919998,132.169998,131.470001,132.539993,133.039993,133.470001,133.139999,134.460007,131.899994,134.949997,135.759995,133.800003,129.690002,131.779999,128.899994,130.800003,132.5,130.839996,130.440002,133.910004,136.910004,138.880005,139.009995,135.199997,131.009995,129.979996,131.059998,131.919998]]},"evals":[],"jsHooks":[]}</script>
<p><br /></p>
</div>
</div>
<div id="decomposition-plots" class="section level3">
<h3>Decomposition Plots</h3>
<p>Decomposition of a time series enables you to view it broken out into 3 key components (in addition to observed values):</p>
<ul>
<li>overall <strong>trend</strong></li>
<li><strong>seasonality</strong> trending</li>
<li><strong>randomness</strong> trend (noise)</li>
</ul>
<p>This can make it easier to ‘separate the signal from the noise’ and get a clearer sense of what is going on.</p>
<p>There has to be data over a long enough period to assess any seasonal trend, so this requires:</p>
<ul>
<li><strong>frequency &gt; 1</strong>, where 1=annual data; typically it would be at least 4 (quarterly), 12 (monthly), 52 (weekly), 365 (daily).</li>
<li><strong>period longer than 2 years</strong>: one year is not enough to establish a seasonal <em>pattern</em> over time.
<ul>
<li>if you get <span style="color:red;">‘Error in decomposet(<data>): time series has no or less than 2 periods’</span> it is usually due to violating one or both of the above conditions.</li>
</ul></li>
<li>need to translate xts object to <strong>ts</strong> for this.</li>
</ul>
<pre class="r"><code>## Air Passengers has enough data
ap_decomp &lt;- decompose(AirPassengers)
plot(ap_decomp)</code></pre>
<p><img src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/figure-html/unnamed-chunk-28-1.png" width="768" /></p>
<pre class="r"><code>apx_decomp &lt;- decompose(ts(Air_xts, frequency=12))
plot(apx_decomp)</code></pre>
<p><img src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/figure-html/unnamed-chunk-28-2.png" width="768" /></p>
<ul>
<li>same results with both approaches, although the original ts object maintains dates on x-axis, making it easier to interpret.</li>
<li><strong>interpretation</strong>: steady upward trend; peaks at mid-year; randomness fairly large at first, settles down, then appears to be growing over time.</li>
<li>coincides with what we see in the observed data but makes the patterns more evident.</li>
</ul>
<p>If we fetch some longer daily data for stock price, we can do the same:</p>
<pre class="r"><code>## fetch some longer price data
price_d &lt;- getSymbols(&#39;EA&#39;, from=&#39;2016-01-01&#39;, to=&#39;2021-12-31&#39;, auto.assign = FALSE)
price_decomp &lt;- decompose(ts(price_d$EA.Close, frequency=365), type=&quot;additive&quot;)
plot(price_decomp)</code></pre>
<p><img src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/figure-html/unnamed-chunk-29-1.png" width="768" /></p>
<ul>
<li>we provide 6 full years of data and most of that is used to calculated decomposition.</li>
<li>x-axis is year number.</li>
<li><strong>TREND</strong>: trending up to about half-way through year 2, then down until about the same point in year 3, then back up, looking like a peak in mid year 4. Not willing to stretch out beyond that. ;)</li>
<li><strong>SEASONAL</strong>: pattern has been detected where tends to be a dip at beginning of year, rising up to a peak toward end of first quarter, dropping sharply, smaller peak mid-year, peak in q3 or early q4, drop with a smaller bump at end of year.</li>
<li><strong>RANDOM</strong>: as to be expected with stock price in general, lots of randomness involved!</li>
</ul>
<p>Looks like there may be money to be made riding the seasonal wave! Please: <strong>do <em>not</em> buy or sell stocks</strong> based on this information. ;)</p>
</div>
<div id="forecasting" class="section level3">
<h3>Forecasting</h3>
<p>A primary use case for time series objects is forecasting. This is a whole other, involved topic way beyond the scope of this post.</p>
<p>Here is a quick example to show how easy forecasting can be in R. Note that we need to bring in the <strong>forecast</strong> package for this. (There is also the amazing <strong>[tidyverts eco-system]</strong>(<a href="https://tidyverts.org/" class="uri">https://tidyverts.org/</a>) for working with time series that I have recently discovered - again, a whole other topic for another time.)</p>
<div id="get-an-arima-model" class="section level4">
<h4>Get an ARIMA Model</h4>
<p>Some basic terms, over-simplified for our purposes here:</p>
<ul>
<li><strong>ARIMA</strong> stands for <strong>A</strong>uto <strong>R</strong>egression <strong>I</strong>ntegrated <strong>M</strong>oving <strong>A</strong>verage</li>
<li>One of the most widely-used time series forecasting methods, although certainly not the only.</li>
<li>3 essential parameters for ARIMA are p,d,q: p=periods of lag, d=differencing, q=error of the model.</li>
</ul>
<pre class="r"><code>library(forecast)
## get closing prices for forecasting
price_cl &lt;- price[,4]
## get a model for the time series - using auto.arima for simplicity
fitA &lt;- auto.arima(price_cl, seasonal=FALSE) ## can add trace=TRUE to see comparison of different models 
## show model
fitA</code></pre>
<pre><code>## Series: price_cl 
## ARIMA(0,1,1) 
## 
## Coefficients:
##          ma1
##       -0.084
## s.e.   0.043
## 
## sigma^2 estimated as 5.64:  log likelihood=-1194
## AIC=2392   AICc=2392   BIC=2400</code></pre>
<p>The model we get back is <strong>ARIMA(0,1,1)</strong> which means p=0, d=1, q=1. We can generate a model by setting these parameters manually, but <strong>auto.arima</strong> automatically checks a variety of models and selects the best. When comparing models, lowest AIC and BIC are preferred.</p>
<p>We can check the accuracy of the model. Most useful item here for interpretation and comparison is MAPE (mean average percent error). In this case,</p>
<pre class="r"><code>## check accuracy - based on historical data
accuracy(fitA)</code></pre>
<pre><code>##                  ME RMSE  MAE    MPE MAPE  MASE     ACF1
## Training set 0.0513 2.37 1.76 0.0225 1.39 0.998 -0.00169</code></pre>
<pre class="r"><code>fitAa &lt;- accuracy(fitA)
100-fitAa[,5]</code></pre>
<pre><code>## [1] 98.6</code></pre>
<p>So in this case a MAPE of 1.386 can be seen as accuracy of 98.614%.</p>
<p>We can also plot the residuals of the model for visual inspection.</p>
<pre class="r"><code>## check residuals
tsdisplay(residuals(fitA), main=&#39;Residuals of Simple ARIMA Forecasting Model for Stock Price&#39;)</code></pre>
<p><img src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/figure-html/unnamed-chunk-32-1.png" width="768" /></p>
<p>As usual with residuals, we are looking for mean around 0, roughly evenly distributed. For ARIMA we also get ACF and PACF, where we are looking for bars to be short and at least within blue dotted lines. So looks like we are good to go here.</p>
</div>
<div id="create-a-forecast" class="section level4">
<h4>Create A Forecast</h4>
<p>We just need a little more code to create and plot forecast. We can set the forecast period for whatever we want, based on the periodicity of the data, in this case days and we are looking out 30 days.</p>
<pre class="r"><code>days=30
fcastA &lt;- forecast(fitA, h=days)
plot(fcastA)</code></pre>
<p><img src="http://www.catbird-analytics.com/post/r-time-series-vs-data-frames/index_files/figure-html/unnamed-chunk-33-1.png" width="768" /></p>
<p>That was easy! And we can use this approach to quickly iterate over various models, if we are not convinced that auto.arima is the best. Of course you can use data frames to create forecasts of various sorts but the xts object makes it super-easy to apply common time series methods.</p>
<p>This also reveals a shortcoming of times-series forecasting:</p>
<ul>
<li>dependence of <strong>pattern recognition</strong> and <strong>pattern repetition</strong>, which can lead to conservative forecast, especially with noisy data.</li>
<li>as a result, the forecast is: <em>‘steady as she goes, with possibility of moving either quite a bit higher or quite a bit lower’.</em></li>
</ul>
<p>So not that useful. To be fair, if stock market prices are not actually predictable, so it is a perfectly reasonable outcome that grounds us in reality.</p>
</div>
</div>
<div id="conclusion" class="section level3">
<h3>Conclusion</h3>
<p>Times series objects are obviously a powerful way to work with time-based data and a go-to when your data is based on time. Particular strengths inculde:</p>
<ul>
<li>Ease of <strong>manipulation</strong> such as aggregation by date periods, selecting date ranges, period calculations.</li>
<li>Some great <strong>visualization</strong> options for exploring the data.</li>
<li><strong>Forecasting</strong> which is really the bread and butter of time series objects.</li>
</ul>
<p>There are some cases where you may prefer to stick with data frames:</p>
<ul>
<li><strong>Multi-dimensional data</strong>: time series work best when each row represents a distinct time. If you are dealing with multi-dimensional data where dates are broken down by customer, or region, etc., especially in tidy format, you may want to stick with data frame.</li>
<li><strong>Visualization preferences</strong>: if you are more comfortable with using ggplot2 (or other visualization tools geared toward data frames) a data frame may be preferable. Or if the document you are producing has ggplot2 charts, you may want to maintain standard presentation.</li>
<li><strong>Forecasting needs</strong>: if you are doing time series forecasting you will want to use a time series object. If you’re not doing forecasting, there is less of a need. Limitation is that time series forecasting is based only on historical trends in the data and doesn’t include things like correlation with other factors.</li>
</ul>
<p>Ultimately, the right tool for the job depends on a variety of situational factors, and having a collection of tools at your disposal helps you avoid the ‘when you have is a hammer…’ pitfall. If your data is based on time, time series should be in consideration.</p>
<p>So that’s quite a lot for one blog post - hopefully helps you make the most of your ‘time’!</p>
</div>
<div id="resources" class="section level3">
<h3>Resources</h3>
<p>Additional resources that may be helpful with time-series and xts in particular:</p>
<ul>
<li><a href="http://datacamp-community-prod.s3.amazonaws.com/72771032-0653-4d87-a798-4a83879e99c8">xts Cheat Sheet</a>.</li>
<li><a href="https://www.datacamp.com/community/blog/r-xts-cheat-sheet">supplementary info. to cheat sheet</a>.</li>
<li><a href="https://cran.r-project.org/web/packages/xts/xts.pdf">xts package vignette</a>.</li>
<li><a href="https://rc2e.com/timeseriesanalysis">time series section in R Cookbook 2nd Edition</a>.</li>
<li><a href="https://tsibble.tidyverts.org/">tsibble package info.</a> - time series for tidyverse.</li>
</ul>
</div>

		</div>
		<footer class="post__footer">
			
<div class="post__tags tags clearfix">
	<svg class="tags__badge icon icon-tag" width="16" height="16" viewBox="0 0 32 32"><path d="M32 19c0 1-1 2-1 2L21 31s-1 1-2 1-2-1-2-1L2 16c-1-1-1.4-2-1.4-2S0 12.5 0 11V3C0 1.5.8.8.8.8S1.5 0 3 0h8c1.5 0 3 .6 3 .6S15 1 16 2l15 15s1 1 1 2zM7 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/></svg>
	<ul class="tags__list">
		<li class="tags__item">
			<a class="tags__link btn" href="/tags/dataviz/" rel="tag">dataviz</a>
		</li>
		<li class="tags__item">
			<a class="tags__link btn" href="/tags/r-markdown/" rel="tag">R Markdown</a>
		</li>
		<li class="tags__item">
			<a class="tags__link btn" href="/tags/time-series/" rel="tag">time-series</a>
		</li>
	</ul>
</div>
		</footer>
	</article>
</main>

<div class="authorbox clearfix">
	<figure class="authorbox__avatar">
		<img alt="John Yuill avatar" src="/img/avatar.png" class="avatar" height="90" width="90">
	</figure>
	<div class="authorbox__header">
		<span class="authorbox__name">About John Yuill</span>
	</div>
	<div class="authorbox__description">
		I&rsquo;m passionate about using data and analytics to understand the world better, improve decision-making, and more effectively achieve goals.
	</div>
</div>

<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/post/google-trends-r-gtrends-for-power-analytics/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Google Trends &#43; R: gtrendsR for Powerful Trend Analytics</p>
		</a>
	</div>
</nav>


			</div>
			<aside class="sidebar"><div class="widget-search widget">
	<form class="widget-search__form" role="search" method="get" action="https://google.com/search">
		<label>
			<input class="widget-search__field" type="search" placeholder="SEARCH…" value="" name="q" aria-label="SEARCH…">
		</label>
		<input class="widget-search__submit" type="submit" value="Search">
		<input type="hidden" name="sitesearch" value="http://www.catbird-analytics.com" />
	</form>
</div>
<div class="widget-social widget">
	<h4 class="widget-social__title widget__title">Social</h4>
	<div class="widget-social__content widget__content">
		<div class="widget-social__item widget__item">
			<a class="widget-social__link widget__link btn" title="LinkedIn" rel="noopener noreferrer" href="https://linkedin.com/in/johnyuill" target="_blank">
				<svg class="widget-social__link-icon icon icon-linkedin" width="24" height="24" viewBox="0 0 352 352"><path d="M0,40v272c0,21.9,18.1,40,40,40h272c21.9,0,40-18.1,40-40V40c0-21.9-18.1-40-40-40H40C18.1,0,0,18.1,0,40z M312,32 c4.6,0,8,3.4,8,8v272c0,4.6-3.4,8-8,8H40c-4.6,0-8-3.4-8-8V40c0-4.6,3.4-8,8-8H312z M59.5,87c0,15.2,12.3,27.5,27.5,27.5 c15.2,0,27.5-12.3,27.5-27.5c0-15.2-12.3-27.5-27.5-27.5C71.8,59.5,59.5,71.8,59.5,87z M187,157h-1v-21h-45v152h47v-75 c0-19.8,3.9-39,28.5-39c24.2,0,24.5,22.4,24.5,40v74h47v-83.5c0-40.9-8.7-72-56.5-72C208.5,132.5,193.3,145.1,187,157z M64,288h47.5 V136H64V288z"/></svg>
				<span>LinkedIn</span>
			</a>
		</div>
		<div class="widget-social__item widget__item">
			<a class="widget-social__link widget__link btn" title="GitHub" rel="noopener noreferrer" href="https://github.com/jyuill" target="_blank">
				<svg class="widget-social__link-icon icon icon-github" width="24" height="24" viewBox="0 0 384 374"><path d="m192 0c-106.1 0-192 85.8-192 191.7 0 84.7 55 156.6 131.3 181.9 9.6 1.8 13.1-4.2 13.1-9.2 0-4.6-.2-16.6-.3-32.6-53.4 11.6-64.7-25.7-64.7-25.7-8.7-22.1-21.3-28-21.3-28-17.4-11.9 1.3-11.6 1.3-11.6 19.3 1.4 29.4 19.8 29.4 19.8 17.1 29.3 44.9 20.8 55.9 15.9 1.7-12.4 6.7-20.8 12.2-25.6-42.6-4.8-87.5-21.3-87.5-94.8 0-20.9 7.5-38 19.8-51.4-2-4.9-8.6-24.3 1.9-50.7 0 0 16.1-5.2 52.8 19.7 15.3-4.2 31.7-6.4 48.1-6.5 16.3.1 32.7 2.2 48.1 6.5 36.7-24.8 52.8-19.7 52.8-19.7 10.5 26.4 3.9 45.9 1.9 50.7 12.3 13.4 19.7 30.5 19.7 51.4 0 73.7-44.9 89.9-87.7 94.6 6.9 5.9 13 17.6 13 35.5 0 25.6-.2 46.3-.2 52.6 0 5.1 3.5 11.1 13.2 9.2 76.2-25.5 131.2-97.3 131.2-182 0-105.9-86-191.7-192-191.7z"/></svg>
				<span>GitHub</span>
			</a>
		</div>

		
	</div>
</div>
<div class="widget-recent widget">
	<h4 class="widget__title">Recent Posts</h4>
	<div class="widget__content">
		<ul class="widget__list">
			<li class="widget__item"><a class="widget__link" href="/post/r-time-series-vs-data-frames/">R Time Series Objects vs Data Frames: Advantages and Limitations</a></li>
			<li class="widget__item"><a class="widget__link" href="/post/google-trends-r-gtrends-for-power-analytics/">Google Trends &#43; R: gtrendsR for Powerful Trend Analytics</a></li>
		</ul>
	</div>
</div>
<div class="widget-categories widget">
	<h4 class="widget__title">Categories</h4>
	<div class="widget__content">
		<ul class="widget__list">
			<li class="widget__item">
				<a class="widget__link" href="/categories/r/">R</a></li>
		</ul>
	</div>
</div>
<div class="widget-taglist widget">
	<h4 class="widget__title">Tags</h4>
	<div class="widget__content">
		<a class="widget-taglist__link widget__link btn" href="/tags/dataviz/" title="dataviz">dataviz</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/google-trends/" title="google trends">google trends</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/gtrendsr/" title="gtrendsR">gtrendsR</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/r-markdown/" title="R Markdown">R Markdown</a>
		<a class="widget-taglist__link widget__link btn" href="/tags/time-series/" title="time-series">time-series</a>
	</div>
</div>
</aside>
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2022 Catbird Analytics.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>